package com.zillit.desktop.core.designsystem.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

// GENERATED by scripts/gen-ah-icons.py from zillit_web/src/accountHub/icons/index.jsx.
// Do not hand-edit: re-run the script when the web's bundle changes.

/**
 * The Account Hub's own glyph set — 147 24×24 stroke icons the web
 * drew for exactly these modules (purchase order, invoice, card and cash
 * expense, payroll, cost report, ledger, vendor, approver, …).
 *
 * The console used [ZillitIcons]' nearest generic shape for each row, so
 * Invoices and Bible Report were the same page glyph and Payroll and Bank
 * Reconciliation the same bank; the web gives each module its own. Tint these
 * like any other icon — every path is drawn in black and [ZillitIcon] recolours
 * it. Built lazily: the console uses a handful of the set.
 */
@Suppress("LargeClass") // A generated glyph table; one property per icon is the API.
object AhIcons {

    /** Web `check`. */
    val Check: ImageVector by lazy {
        glyph(
            "check",
            s("M4.5 12.5 L9.5 17.5 L19.5 6.5"),
        )
    }

    /** Web `copy`. */
    val Copy: ImageVector by lazy {
        glyph(
            "copy",
            s("M10.2 8 H17.8 A2.2 2.2 0 0 1 20 10.2 V17.8 A2.2 2.2 0 0 1 17.8 20 H10.2 A2.2 2.2 " +
                "0 0 1 8 17.8 V10.2 A2.2 2.2 0 0 1 10.2 8 Z"),
            s("M16 8 V5.6 A2 2 0 0 0 14 3.6 H6 A2 2 0 0 0 4 5.6 V14 A2 2 0 0 0 6 16 H8"),
        )
    }

    /** Web `cut`. */
    val Cut: ImageVector by lazy {
        glyph(
            "cut",
            s("M3.9 6.5 A2.6 2.6 0 1 0 9.1 6.5 A2.6 2.6 0 1 0 3.9 6.5 Z"),
            s("M3.9 17.5 A2.6 2.6 0 1 0 9.1 17.5 A2.6 2.6 0 1 0 3.9 17.5 Z"),
            s("M8.7 8.3 L20 17.5"),
            s("M20 6.5 L8.7 15.7"),
        )
    }

    /** Web `edit`. */
    val Edit: ImageVector by lazy {
        glyph(
            "edit",
            s("M4 20 L4.9 16 L16.4 4.5 A2 2 0 0 1 19.5 7.6 L8 19.1 Z"),
            s("M14.2 6.7 L17.3 9.8"),
        )
    }

    /** Web `filter`. */
    val Filter: ImageVector by lazy {
        glyph(
            "filter",
            s("M3.5 5 H20.5 L13.8 13 V19 L10.2 21 V13 Z"),
        )
    }

    /** Web `minus`. */
    val Minus: ImageVector by lazy {
        glyph(
            "minus",
            s("M5 12 L19 12"),
        )
    }

    /** Web `paste`. */
    val Paste: ImageVector by lazy {
        glyph(
            "paste",
            s("M9 4.6 H7 A1.6 1.6 0 0 0 5.4 6.2 V19 A1.6 1.6 0 0 0 7 20.6 H17 A1.6 1.6 0 0 0 " +
                "18.6 19 V6.2 A1.6 1.6 0 0 0 17 4.6 H15"),
            s("M10.1 2.8 H13.9 A1.1 1.1 0 0 1 15 3.9 V5.1 A1.1 1.1 0 0 1 13.9 6.2 H10.1 A1.1 " +
                "1.1 0 0 1 9 5.1 V3.9 A1.1 1.1 0 0 1 10.1 2.8 Z"),
            s("M8.5 11.5 L15.5 11.5"),
            s("M8.5 15 L13 15"),
        )
    }

    /** Web `plus`. */
    val Plus: ImageVector by lazy {
        glyph(
            "plus",
            s("M12 5 L12 19"),
            s("M5 12 L19 12"),
        )
    }

    /** Web `redo`. */
    val Redo: ImageVector by lazy {
        glyph(
            "redo",
            s("M19.4 11 H10 A4.6 4.6 0 0 0 10 20.2 H15.5"),
            s("M15.8 7 L19.4 11 L15.8 15"),
        )
    }

    /** Web `refresh`. */
    val Refresh: ImageVector by lazy {
        glyph(
            "refresh",
            s("M20 8 A8.4 8.4 0 0 0 5.2 8.4"),
            s("M20 4.4 V8 H16.4"),
            s("M4 16 A8.4 8.4 0 0 0 18.8 15.6"),
            s("M4 19.6 V16 H7.6"),
        )
    }

    /** Web `search`. */
    val Search: ImageVector by lazy {
        glyph(
            "search",
            s("M4 10.5 A6.5 6.5 0 1 0 17 10.5 A6.5 6.5 0 1 0 4 10.5 Z"),
            s("M15.2 15.2 L20 20"),
        )
    }

    /** Web `sort-ascending`. */
    val SortAscending: ImageVector by lazy {
        glyph(
            "sort-ascending",
            s("M4 7 L12 7"),
            s("M4 12 L10 12"),
            s("M4 17 L8 17"),
            s("M17 18.5 V6"),
            s("M14 9 L17 6 L20 9"),
        )
    }

    /** Web `sort-descending`. */
    val SortDescending: ImageVector by lazy {
        glyph(
            "sort-descending",
            s("M4 7 L8 7"),
            s("M4 12 L10 12"),
            s("M4 17 L12 17"),
            s("M17 5.5 V18"),
            s("M14 15 L17 18 L20 15"),
        )
    }

    /** Web `trash`. */
    val Trash: ImageVector by lazy {
        glyph(
            "trash",
            s("M4 6.4 L20 6.4"),
            s("M9 6.4 V4.6 H15 V6.4"),
            s("M6.2 6.4 L7 19.4 A1.4 1.4 0 0 0 8.4 20.7 H15.6 A1.4 1.4 0 0 0 17 19.4 L17.8 6.4"),
            s("M10 10 L10 17"),
            s("M14 10 L14 17"),
        )
    }

    /** Web `undo`. */
    val Undo: ImageVector by lazy {
        glyph(
            "undo",
            s("M4.6 11 H14 A4.6 4.6 0 0 1 14 20.2 H8.5"),
            s("M8.2 7 L4.6 11 L8.2 15"),
        )
    }

    /** Web `x`. */
    val X: ImageVector by lazy {
        glyph(
            "x",
            s("M6 6 L18 18"),
            s("M18 6 L6 18"),
        )
    }

    /** Web `fingerprint`. */
    val Fingerprint: ImageVector by lazy {
        glyph(
            "fingerprint",
            s("M3.9 10.5 A8.5 8.5 0 0 1 20.1 10.5"),
            s("M6.4 16.5 C6.4 11 8.9 8 12 8 C15.1 8 17.6 11 17.6 16.5"),
            s("M8.8 17.4 C8.8 12.6 10.1 10.4 12 10.4 C13.9 10.4 15.2 12.6 15.2 17"),
            s("M11 18 C11 14.8 11.2 12.8 12 12.8 C12.8 12.8 13 14.8 13 16.4"),
        )
    }

    /** Web `key`. */
    val Key: ImageVector by lazy {
        glyph(
            "key",
            s("M3.7 14.5 A3.8 3.8 0 1 0 11.3 14.5 A3.8 3.8 0 1 0 3.7 14.5 Z"),
            s("M10.2 11.8 L20 2"),
            s("M15.5 6.5 L18 9 M17.6 4.4 L20.1 6.9"),
        )
    }

    /** Web `lock-open`. */
    val LockOpen: ImageVector by lazy {
        glyph(
            "lock-open",
            s("M7 10.4 H17 A2.4 2.4 0 0 1 19.4 12.8 V18.6 A2.4 2.4 0 0 1 17 21 H7 A2.4 2.4 0 0 " +
                "1 4.6 18.6 V12.8 A2.4 2.4 0 0 1 7 10.4 Z"),
            s("M7.6 10.4 V7.4 A4.4 4.4 0 0 1 16 5.6"),
            s("M10.8 15 A1.2 1.2 0 1 0 13.2 15 A1.2 1.2 0 1 0 10.8 15 Z"),
            s("M12 16.2 L12 18"),
        )
    }

    /** Web `lock`. */
    val Lock: ImageVector by lazy {
        glyph(
            "lock",
            s("M7 10.4 H17 A2.4 2.4 0 0 1 19.4 12.8 V18.6 A2.4 2.4 0 0 1 17 21 H7 A2.4 2.4 0 0 " +
                "1 4.6 18.6 V12.8 A2.4 2.4 0 0 1 7 10.4 Z"),
            s("M7.6 10.4 V7.4 A4.4 4.4 0 0 1 16.4 7.4 V10.4"),
            s("M10.8 15 A1.2 1.2 0 1 0 13.2 15 A1.2 1.2 0 1 0 10.8 15 Z"),
            s("M12 16.2 L12 18"),
        )
    }

    /** Web `login`. */
    val Login: ImageVector by lazy {
        glyph(
            "login",
            s("M10 4 H17.4 A1.6 1.6 0 0 1 19 5.6 V18.4 A1.6 1.6 0 0 1 17.4 20 H10"),
            s("M3.5 12 L14 12"),
            s("M10 8 L14 12 L10 16"),
        )
    }

    /** Web `logout`. */
    val Logout: ImageVector by lazy {
        glyph(
            "logout",
            s("M14 4 H6.6 A1.6 1.6 0 0 0 5 5.6 V18.4 A1.6 1.6 0 0 0 6.6 20 H14"),
            s("M10 12 L20.5 12"),
            s("M16.5 8 L20.5 12 L16.5 16"),
        )
    }

    /** Web `shield`. */
    val Shield: ImageVector by lazy {
        glyph(
            "shield",
            s("M12 2.6 L20 5.6 V11.2 C20 16 16.6 19.6 12 21.4 C7.4 19.6 4 16 4 11.2 V5.6 Z"),
        )
    }

    /** Web `user-minus`. */
    val UserMinus: ImageVector by lazy {
        glyph(
            "user-minus",
            s("M6.2 8 A3.2 3.2 0 1 0 12.6 8 A3.2 3.2 0 1 0 6.2 8 Z"),
            s("M3.8 19 C4.7 15.4 6.9 13.8 9.4 13.8 C10.4 13.8 11.4 14 12.2 14.5"),
            s("M14.5 17.5 L20.5 17.5"),
        )
    }

    /** Web `user-plus`. */
    val UserPlus: ImageVector by lazy {
        glyph(
            "user-plus",
            s("M6.2 8 A3.2 3.2 0 1 0 12.6 8 A3.2 3.2 0 1 0 6.2 8 Z"),
            s("M3.8 19 C4.7 15.4 6.9 13.8 9.4 13.8 C10.4 13.8 11.4 14 12.2 14.5"),
            s("M17.5 14.5 L17.5 20.5"),
            s("M14.5 17.5 L20.5 17.5"),
        )
    }

    /** Web `user`. */
    val User: ImageVector by lazy {
        glyph(
            "user",
            s("M8.6 8 A3.4 3.4 0 1 0 15.4 8 A3.4 3.4 0 1 0 8.6 8 Z"),
            s("M5.6 19.4 C6.6 15.5 9 13.8 12 13.8 C15 13.8 17.4 15.5 18.4 19.4"),
        )
    }

    /** Web `users`. */
    val Users: ImageVector by lazy {
        glyph(
            "users",
            s("M5.8 8.6 A3.2 3.2 0 1 0 12.2 8.6 A3.2 3.2 0 1 0 5.8 8.6 Z"),
            s("M3.6 18.4 C4.4 15 6.5 13.4 9 13.4 C11.5 13.4 13.6 15 14.4 18.4"),
            s("M14.6 7.6 A2.4 2.4 0 1 0 19.4 7.6 A2.4 2.4 0 1 0 14.6 7.6 Z"),
            s("M15.6 13.5 C16 13.4 16.5 13.4 17 13.4 C19.3 13.4 21.1 14.9 21.7 17.6"),
        )
    }

    /** Web `at`. */
    val At: ImageVector by lazy {
        glyph(
            "at",
            s("M8.6 12 A3.4 3.4 0 1 0 15.4 12 A3.4 3.4 0 1 0 8.6 12 Z"),
            s("M15.4 12 V13.6 A2.6 2.6 0 0 0 20.6 13.6 V12 A8.6 8.6 0 1 0 16.4 19.4"),
        )
    }

    /** Web `bell-off`. */
    val BellOff: ImageVector by lazy {
        glyph(
            "bell-off",
            s("M8.6 5.6 A5.6 5.6 0 0 1 17.6 11 V16.8 L18.8 18.4"),
            s("M16.4 19.4 H4.4 L6.4 16.8 V11 A5.6 5.6 0 0 1 7 8.6"),
            s("M10 19.4 A2 2 0 0 0 14 19.4"),
            s("M4 3.8 L20 20.2"),
        )
    }

    /** Web `bell`. */
    val Bell: ImageVector by lazy {
        glyph(
            "bell",
            s("M6.4 16.8 V11 A5.6 5.6 0 0 1 17.6 11 V16.8 L19.6 19.4 H4.4 Z"),
            s("M10 19.4 A2 2 0 0 0 14 19.4"),
        )
    }

    /** Web `link`. */
    val Link: ImageVector by lazy {
        glyph(
            "link",
            s("M10.4 13.6 A4 4 0 0 1 10.4 7.9 L13 5.3 A4 4 0 0 1 18.7 11 L17.2 12.5"),
            s("M13.6 10.4 A4 4 0 0 1 13.6 16.1 L11 18.7 A4 4 0 0 1 5.3 13 L6.8 11.5"),
        )
    }

    /** Web `mail`. */
    val Mail: ImageVector by lazy {
        glyph(
            "mail",
            s("M5.2 5.5 H18.8 A2.2 2.2 0 0 1 21 7.7 V16.3 A2.2 2.2 0 0 1 18.8 18.5 H5.2 A2.2 " +
                "2.2 0 0 1 3 16.3 V7.7 A2.2 2.2 0 0 1 5.2 5.5 Z"),
            s("M3.6 7 L12 13 L20.4 7"),
        )
    }

    /** Web `message-circle`. */
    val MessageCircle: ImageVector by lazy {
        glyph(
            "message-circle",
            s("M12 3.6 A8 8 0 1 1 6.5 17.4 L4 20 L5 16.2 A8 8 0 0 1 12 3.6 Z"),
            f("M8.45 11.5 A0.55 0.55 0 1 0 9.55 11.5 A0.55 0.55 0 1 0 8.45 11.5 Z"),
            f("M11.45 11.5 A0.55 0.55 0 1 0 12.55 11.5 A0.55 0.55 0 1 0 11.45 11.5 Z"),
            f("M14.45 11.5 A0.55 0.55 0 1 0 15.55 11.5 A0.55 0.55 0 1 0 14.45 11.5 Z"),
        )
    }

    /** Web `message`. */
    val Message: ImageVector by lazy {
        glyph(
            "message",
            s("M4 5.6 A1.8 1.8 0 0 1 5.8 3.8 H18.2 A1.8 1.8 0 0 1 20 5.6 V14.4 A1.8 1.8 0 0 1 " +
                "18.2 16.2 H9 L4.6 19.6 V16.2 A1.8 1.8 0 0 1 4 14.4 Z"),
            s("M7.5 8.2 L16.5 8.2"),
            s("M7.5 11.6 L13 11.6"),
        )
    }

    /** Web `phone`. */
    val Phone: ImageVector by lazy {
        glyph(
            "phone",
            s("M5.5 4 H8 Q8.7 4 9 4.6 L10.2 8.6 Q10.5 9.3 9.9 9.8 L8 11 C9 13.2 10.8 15 13 16 " +
                "L14.2 14.1 Q14.7 13.5 15.4 13.8 L19.4 15 Q20 15.2 20 15.9 V18.8 A1.7 1.7 0 0 1 " +
                "18.1 20.5 C10.2 20 4 13.8 3.5 5.9 A1.7 1.7 0 0 1 5.5 4 Z"),
        )
    }

    /** Web `send`. */
    val Send: ImageVector by lazy {
        glyph(
            "send",
            s("M21 3.4 L10.6 13.8"),
            s("M21 3.4 L14.4 21 L10.6 13.8 L3 9.6 Z"),
        )
    }

    /** Web `video`. */
    val Video: ImageVector by lazy {
        glyph(
            "video",
            s("M5.2 6.5 H13.8 A2.2 2.2 0 0 1 16 8.7 V15.3 A2.2 2.2 0 0 1 13.8 17.5 H5.2 A2.2 " +
                "2.2 0 0 1 3 15.3 V8.7 A2.2 2.2 0 0 1 5.2 6.5 Z"),
            s("M16 11 L21 8 V16 L16 13 Z"),
        )
    }

    /** Web `alert-circle`. */
    val AlertCircle: ImageVector by lazy {
        glyph(
            "alert-circle",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M12 7.5 L12 13"),
            f("M11.5 16.3 A0.5 0.5 0 1 0 12.5 16.3 A0.5 0.5 0 1 0 11.5 16.3 Z"),
        )
    }

    /** Web `alert-triangle`. */
    val AlertTriangle: ImageVector by lazy {
        glyph(
            "alert-triangle",
            s("M10.9 4.3 Q12 2.4 13.1 4.3 L21.3 18.6 Q22.4 20.5 20.2 20.5 H3.8 Q1.6 20.5 2.7 " +
                "18.6 Z"),
            s("M12 9.6 L12 14"),
            f("M11.5 16.8 A0.5 0.5 0 1 0 12.5 16.8 A0.5 0.5 0 1 0 11.5 16.8 Z"),
        )
    }

    /** Web `columns`. */
    val Columns: ImageVector by lazy {
        glyph(
            "columns",
            s("M5.7 4 H18.3 A2.2 2.2 0 0 1 20.5 6.2 V17.8 A2.2 2.2 0 0 1 18.3 20 H5.7 A2.2 2.2 " +
                "0 0 1 3.5 17.8 V6.2 A2.2 2.2 0 0 1 5.7 4 Z"),
            s("M12 4 L12 20"),
        )
    }

    /** Web `eye-off`. */
    val EyeOff: ImageVector by lazy {
        glyph(
            "eye-off",
            s("M10.7 6.1 A9 9 0 0 1 12 6 C16 6 19.5 8.5 21.5 12 A12.6 12.6 0 0 1 19.4 14.9"),
            s("M6.6 6.6 A12.6 12.6 0 0 0 2.5 12 C4.5 15.5 8 18 12 18 A8.8 8.8 0 0 0 15.1 17.4"),
            s("M9.9 9.9 A3 3 0 0 0 14.1 14.1"),
            s("M3.5 3.5 L20.5 20.5"),
        )
    }

    /** Web `eye`. */
    val Eye: ImageVector by lazy {
        glyph(
            "eye",
            s("M2.5 12 C5 7.2 9 5.2 12 5.2 C15 5.2 19 7.2 21.5 12 C19 16.8 15 18.8 12 18.8 C9 " +
                "18.8 5 16.8 2.5 12 Z"),
            s("M8.9 12 A3.1 3.1 0 1 0 15.1 12 A3.1 3.1 0 1 0 8.9 12 Z"),
        )
    }

    /** Web `grid`. */
    val Grid: ImageVector by lazy {
        glyph(
            "grid",
            s("M5.1 3.5 H8.9 A1.6 1.6 0 0 1 10.5 5.1 V8.9 A1.6 1.6 0 0 1 8.9 10.5 H5.1 A1.6 1.6 " +
                "0 0 1 3.5 8.9 V5.1 A1.6 1.6 0 0 1 5.1 3.5 Z"),
            s("M15.1 3.5 H18.9 A1.6 1.6 0 0 1 20.5 5.1 V8.9 A1.6 1.6 0 0 1 18.9 10.5 H15.1 A1.6 " +
                "1.6 0 0 1 13.5 8.9 V5.1 A1.6 1.6 0 0 1 15.1 3.5 Z"),
            s("M5.1 13.5 H8.9 A1.6 1.6 0 0 1 10.5 15.1 V18.9 A1.6 1.6 0 0 1 8.9 20.5 H5.1 A1.6 " +
                "1.6 0 0 1 3.5 18.9 V15.1 A1.6 1.6 0 0 1 5.1 13.5 Z"),
            s("M15.1 13.5 H18.9 A1.6 1.6 0 0 1 20.5 15.1 V18.9 A1.6 1.6 0 0 1 18.9 20.5 H15.1 " +
                "A1.6 1.6 0 0 1 13.5 18.9 V15.1 A1.6 1.6 0 0 1 15.1 13.5 Z"),
        )
    }

    /** Web `help-circle`. */
    val HelpCircle: ImageVector by lazy {
        glyph(
            "help-circle",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M9.4 9.4 A2.7 2.7 0 0 1 14.6 10.3 C14.6 12.2 12 12.6 12 14.4"),
            f("M11.5 17.4 A0.5 0.5 0 1 0 12.5 17.4 A0.5 0.5 0 1 0 11.5 17.4 Z"),
        )
    }

    /** Web `info`. */
    val Info: ImageVector by lazy {
        glyph(
            "info",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M12 11 L12 16.4"),
            f("M11.5 7.8 A0.5 0.5 0 1 0 12.5 7.8 A0.5 0.5 0 1 0 11.5 7.8 Z"),
        )
    }

    /** Web `layout`. */
    val Layout: ImageVector by lazy {
        glyph(
            "layout",
            s("M5.7 4 H18.3 A2.2 2.2 0 0 1 20.5 6.2 V17.8 A2.2 2.2 0 0 1 18.3 20 H5.7 A2.2 2.2 " +
                "0 0 1 3.5 17.8 V6.2 A2.2 2.2 0 0 1 5.7 4 Z"),
            s("M3.5 9 L20.5 9"),
            s("M9.5 9 L9.5 20"),
        )
    }

    /** Web `list`. */
    val List: ImageVector by lazy {
        glyph(
            "list",
            s("M3.5 6 A1.1 1.1 0 1 0 5.7 6 A1.1 1.1 0 1 0 3.5 6 Z"),
            s("M3.5 12 A1.1 1.1 0 1 0 5.7 12 A1.1 1.1 0 1 0 3.5 12 Z"),
            s("M3.5 18 A1.1 1.1 0 1 0 5.7 18 A1.1 1.1 0 1 0 3.5 18 Z"),
            s("M8.4 6 L20 6"),
            s("M8.4 12 L20 12"),
            s("M8.4 18 L20 18"),
        )
    }

    /** Web `maximize`. */
    val Maximize: ImageVector by lazy {
        glyph(
            "maximize",
            s("M9 4 H4 V9"),
            s("M15 4 H20 V9"),
            s("M20 15 V20 H15"),
            s("M4 15 V20 H9"),
        )
    }

    /** Web `minimize`. */
    val Minimize: ImageVector by lazy {
        glyph(
            "minimize",
            s("M4 9 H9 V4"),
            s("M20 9 H15 V4"),
            s("M15 20 V15 H20"),
            s("M9 20 V15 H4"),
        )
    }

    /** Web `settings`. */
    val Settings: ImageVector by lazy {
        glyph(
            "settings",
            s("M12 2.6 V4.9 M12 19.1 V21.4 M21.4 12 H19.1 M4.9 12 H2.6 M18.65 5.35 L17.03 6.97 " +
                "M6.97 17.03 L5.35 18.65 M18.65 18.65 L17.03 17.03 M6.97 6.97 L5.35 5.35"),
            s("M7.6 12 A4.4 4.4 0 1 0 16.4 12 A4.4 4.4 0 1 0 7.6 12 Z"),
            s("M10.5 12 A1.5 1.5 0 1 0 13.5 12 A1.5 1.5 0 1 0 10.5 12 Z"),
        )
    }

    /** Web `sliders`. */
    val Sliders: ImageVector by lazy {
        glyph(
            "sliders",
            s("M4 8 L20 8"),
            s("M4 16 L20 16"),
            s("M6.7 8 A2.3 2.3 0 1 0 11.3 8 A2.3 2.3 0 1 0 6.7 8 Z"),
            s("M12.7 16 A2.3 2.3 0 1 0 17.3 16 A2.3 2.3 0 1 0 12.7 16 Z"),
        )
    }

    /** Web `toggle-left`. */
    val ToggleLeft: ImageVector by lazy {
        glyph(
            "toggle-left",
            s("M7 7.5 H17 A4.5 4.5 0 0 1 21.5 12 V12 A4.5 4.5 0 0 1 17 16.5 H7 A4.5 4.5 0 0 1 " +
                "2.5 12 V12 A4.5 4.5 0 0 1 7 7.5 Z"),
            s("M4.4 12 A2.6 2.6 0 1 0 9.6 12 A2.6 2.6 0 1 0 4.4 12 Z"),
        )
    }

    /** Web `toggle-right`. */
    val ToggleRight: ImageVector by lazy {
        glyph(
            "toggle-right",
            s("M7 7.5 H17 A4.5 4.5 0 0 1 21.5 12 V12 A4.5 4.5 0 0 1 17 16.5 H7 A4.5 4.5 0 0 1 " +
                "2.5 12 V12 A4.5 4.5 0 0 1 7 7.5 Z"),
            s("M14.4 12 A2.6 2.6 0 1 0 19.6 12 A2.6 2.6 0 1 0 14.4 12 Z"),
        )
    }

    /** Web `archive`. */
    val Archive: ImageVector by lazy {
        glyph(
            "archive",
            s("M4.4 4 H19.6 A1.4 1.4 0 0 1 21 5.4 V7 A1.4 1.4 0 0 1 19.6 8.4 H4.4 A1.4 1.4 0 0 " +
                "1 3 7 V5.4 A1.4 1.4 0 0 1 4.4 4 Z"),
            s("M4.6 8.4 V18.4 A1.6 1.6 0 0 0 6.2 20 H17.8 A1.6 1.6 0 0 0 19.4 18.4 V8.4"),
            s("M9.6 12.4 L14.4 12.4"),
        )
    }

    /** Web `attachment`. */
    val Attachment: ImageVector by lazy {
        glyph(
            "attachment",
            s("M18.4 11.2 L11.1 18.5 A4.2 4.2 0 0 1 5.2 12.6 L13 4.8 A2.7 2.7 0 0 1 16.8 8.6 " +
                "L9.2 16.2 A1.35 1.35 0 0 1 7.3 14.3 L14 7.6"),
        )
    }

    /** Web `calendar`. */
    val Calendar: ImageVector by lazy {
        glyph(
            "calendar",
            s("M5.8 5 H18.2 A2.4 2.4 0 0 1 20.6 7.4 V18.2 A2.4 2.4 0 0 1 18.2 20.6 H5.8 A2.4 " +
                "2.4 0 0 1 3.4 18.2 V7.4 A2.4 2.4 0 0 1 5.8 5 Z"),
            s("M3.4 9.4 L20.6 9.4"),
            s("M8 3 L8 6.6"),
            s("M16 3 L16 6.6"),
            s("M7.35 13.4 A0.85 0.85 0 1 0 9.05 13.4 A0.85 0.85 0 1 0 7.35 13.4 Z"),
            s("M11.15 13.4 A0.85 0.85 0 1 0 12.85 13.4 A0.85 0.85 0 1 0 11.15 13.4 Z"),
            s("M14.95 13.4 A0.85 0.85 0 1 0 16.65 13.4 A0.85 0.85 0 1 0 14.95 13.4 Z"),
            s("M7.35 16.8 A0.85 0.85 0 1 0 9.05 16.8 A0.85 0.85 0 1 0 7.35 16.8 Z"),
            s("M11.15 16.8 A0.85 0.85 0 1 0 12.85 16.8 A0.85 0.85 0 1 0 11.15 16.8 Z"),
        )
    }

    /** Web `clock`. */
    val Clock: ImageVector by lazy {
        glyph(
            "clock",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M12 6.6 V12 L15.8 14.3"),
        )
    }

    /** Web `document`. */
    val Document: ImageVector by lazy {
        glyph(
            "document",
            s("M6 2.6 H13.4 L18 7.2 V20 A1.4 1.4 0 0 1 16.6 21.4 H7.4 A1.4 1.4 0 0 1 6 20 V4 " +
                "A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.4 H18"),
            s("M8.6 11.4 L15.4 11.4"),
            s("M8.6 14.2 L15.4 14.2"),
            s("M8.6 17 L12.6 17"),
        )
    }

    /** Web `folder`. */
    val Folder: ImageVector by lazy {
        glyph(
            "folder",
            s("M3 7 A2 2 0 0 1 5 5 H9.2 L11.4 7.6 H19 A2 2 0 0 1 21 9.6 V17.4 A2 2 0 0 1 19 " +
                "19.4 H5 A2 2 0 0 1 3 17.4 Z"),
            s("M3 10.4 H21"),
        )
    }

    /** Web `form`. */
    val Form: ImageVector by lazy {
        glyph(
            "form",
            s("M6.2 2.6 H17.8 A2.2 2.2 0 0 1 20 4.8 V19.2 A2.2 2.2 0 0 1 17.8 21.4 H6.2 A2.2 " +
                "2.2 0 0 1 4 19.2 V4.8 A2.2 2.2 0 0 1 6.2 2.6 Z"),
            s("M7 7 L8 8 L9.6 6.2"),
            s("M11.6 7.2 L17 7.2"),
            s("M7 12.2 L8 13.2 L9.6 11.4"),
            s("M11.6 12.4 L17 12.4"),
            s("M7.3 16.2 H8.3 A0.5 0.5 0 0 1 8.8 16.7 V17.7 A0.5 0.5 0 0 1 8.3 18.2 H7.3 A0.5 " +
                "0.5 0 0 1 6.8 17.7 V16.7 A0.5 0.5 0 0 1 7.3 16.2 Z"),
            s("M11.6 17.2 L17 17.2"),
        )
    }

    /** Web `note`. */
    val Note: ImageVector by lazy {
        glyph(
            "note",
            s("M4 6 A2 2 0 0 1 6 4 H18 A2 2 0 0 1 20 6 V13.5 A2 2 0 0 1 18 15.5 H9.6 L5.6 19 " +
                "V15.5 A2 2 0 0 1 4 13.5 Z"),
            s("M7.5 8.4 L16.5 8.4"),
            s("M7.5 11.4 L13 11.4"),
        )
    }

    /** Web `pdf-export`. */
    val PdfExport: ImageVector by lazy {
        glyph(
            "pdf-export",
            s("M6 2.6 H13.4 L18 7.2 V20 A1.4 1.4 0 0 1 16.6 21.4 H7.4 A1.4 1.4 0 0 1 6 20 V4 " +
                "A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.4 H18"),
            s("M12 11 V16.4 M9.6 14 L12 16.4 L14.4 14"),
        )
    }

    /** Web `stamp`. */
    val Stamp: ImageVector by lazy {
        glyph(
            "stamp",
            s("M12 3 A3.4 3.4 0 0 0 8.6 6.4 C8.6 8.4 10 9.4 10.4 11 L13.6 11 C14 9.4 15.4 8.4 " +
                "15.4 6.4 A3.4 3.4 0 0 0 12 3 Z"),
            s("M5.6 17.4 C5.6 15.4 9 14.4 9.6 13.6 H14.4 C15 14.4 18.4 15.4 18.4 17.4 Z"),
            s("M4 20.6 L20 20.6"),
        )
    }

    /** Web `badge`. */
    val Badge: ImageVector by lazy {
        glyph(
            "badge",
            s("M6 9 A6 6 0 1 0 18 9 A6 6 0 1 0 6 9 Z"),
            s("M9 14.3 L8 21 L12 18.8 L16 21 L15 14.3"),
            s("M9.4 9 L11 10.6 L14.6 7"),
        )
    }

    /** Web `bookmark`. */
    val Bookmark: ImageVector by lazy {
        glyph(
            "bookmark",
            s("M7 3.6 H17 Q18 3.6 18 4.6 V20.2 Q18 21.1 17.2 20.5 L12 16.6 L6.8 20.5 Q6 21.1 6 " +
                "20.2 V4.6 Q6 3.6 7 3.6 Z"),
        )
    }

    /** Web `check-circle`. */
    val CheckCircle: ImageVector by lazy {
        glyph(
            "check-circle",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M7.8 12.3 L10.7 15.2 L16.4 8.9"),
        )
    }

    /** Web `flag`. */
    val Flag: ImageVector by lazy {
        glyph(
            "flag",
            s("M6 3.4 L6 21"),
            s("M6 4.6 H17.2 Q18.2 4.6 17.6 5.4 L15.2 8.4 L17.6 11.4 Q18.2 12.2 17.2 12.2 H6"),
        )
    }

    /** Web `heart`. */
    val Heart: ImageVector by lazy {
        glyph(
            "heart",
            s("M12 20.4 C12 20.4 3.5 15.5 3.5 9.4 A4.8 4.8 0 0 1 12 6.4 A4.8 4.8 0 0 1 20.5 9.4 " +
                "C20.5 15.5 12 20.4 12 20.4 Z"),
        )
    }

    /** Web `star`. */
    val Star: ImageVector by lazy {
        glyph(
            "star",
            s("M12 3.4 L14.6 8.9 L20.5 9.7 L16.2 13.9 L17.3 19.9 L12 17 L6.7 19.9 L7.8 13.9 " +
                "L3.5 9.7 L9.4 8.9 Z"),
        )
    }

    /** Web `tag`. */
    val Tag: ImageVector by lazy {
        glyph(
            "tag",
            s("M12.6 2.6 A2 2 0 0 0 11.2 2 H4 A2 2 0 0 0 2 4 V11.2 A2 2 0 0 0 2.6 12.6 L11.3 " +
                "21.3 A2.4 2.4 0 0 0 14.7 21.3 L21.3 14.7 A2.4 2.4 0 0 0 21.3 11.3 Z"),
            s("M6.1 7.5 A1.4 1.4 0 1 0 8.9 7.5 A1.4 1.4 0 1 0 6.1 7.5 Z"),
        )
    }

    /** Web `x-circle`. */
    val XCircle: ImageVector by lazy {
        glyph(
            "x-circle",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M9 9 L15 15"),
            s("M15 9 L9 15"),
        )
    }

    /** Web `cloud-download`. */
    val CloudDownload: ImageVector by lazy {
        glyph(
            "cloud-download",
            s("M7.5 18.5 A4.2 4.2 0 0 1 6.9 10.3 A5.4 5.4 0 0 1 17.4 10.6 A3.7 3.7 0 0 1 16.7 " +
                "18.5"),
            s("M12 12.5 V20.5 M9.6 18.1 L12 20.5 L14.4 18.1"),
        )
    }

    /** Web `cloud-upload`. */
    val CloudUpload: ImageVector by lazy {
        glyph(
            "cloud-upload",
            s("M7.5 18.5 A4.2 4.2 0 0 1 6.9 10.3 A5.4 5.4 0 0 1 17.4 10.6 A3.7 3.7 0 0 1 16.7 " +
                "18.5"),
            s("M12 20.5 V12.5 M9.6 14.9 L12 12.5 L14.4 14.9"),
        )
    }

    /** Web `database`. */
    val Database: ImageVector by lazy {
        glyph(
            "database",
            s("M4.5 5.5 A7.5 2.8 0 1 0 19.5 5.5 A7.5 2.8 0 1 0 4.5 5.5 Z"),
            s("M4.5 5.5 V18.5 C4.5 20 7.9 21.3 12 21.3 C16.1 21.3 19.5 20 19.5 18.5 V5.5"),
            s("M4.5 12 C4.5 13.5 7.9 14.8 12 14.8 C16.1 14.8 19.5 13.5 19.5 12"),
        )
    }

    /** Web `download`. */
    val Download: ImageVector by lazy {
        glyph(
            "download",
            s("M12 4 V15.5 M7.5 11 L12 15.5 L16.5 11"),
            s("M5 14 V18.5 A1.5 1.5 0 0 0 6.5 20 H17.5 A1.5 1.5 0 0 0 19 18.5 V14"),
        )
    }

    /** Web `file-minus`. */
    val FileMinus: ImageVector by lazy {
        glyph(
            "file-minus",
            s("M6 2.6 H13.4 L18 7.2 V20 A1.4 1.4 0 0 1 16.6 21.4 H7.4 A1.4 1.4 0 0 1 6 20 V4 " +
                "A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.4 H18"),
            s("M9 14.6 L15 14.6"),
        )
    }

    /** Web `file-plus`. */
    val FilePlus: ImageVector by lazy {
        glyph(
            "file-plus",
            s("M6 2.6 H13.4 L18 7.2 V20 A1.4 1.4 0 0 1 16.6 21.4 H7.4 A1.4 1.4 0 0 1 6 20 V4 " +
                "A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.4 H18"),
            s("M12 11.6 L12 17.6"),
            s("M9 14.6 L15 14.6"),
        )
    }

    /** Web `file`. */
    val File: ImageVector by lazy {
        glyph(
            "file",
            s("M6 2.6 H13.4 L18 7.2 V20 A1.4 1.4 0 0 1 16.6 21.4 H7.4 A1.4 1.4 0 0 1 6 20 V4 " +
                "A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.4 H18"),
        )
    }

    /** Web `folder-open`. */
    val FolderOpen: ImageVector by lazy {
        glyph(
            "folder-open",
            s("M3.2 17.5 V6.6 A1.8 1.8 0 0 1 5 4.8 H9 L11.2 7.2 H17.6 A1.8 1.8 0 0 1 19.4 9 " +
                "V10.4"),
            s("M5 18.6 L7.5 11.4 A1.4 1.4 0 0 1 8.8 10.4 H21 A1 1 0 0 1 21.95 11.75 L20 17.7 " +
                "A1.6 1.6 0 0 1 18.5 18.8 H4.4"),
        )
    }

    /** Web `upload`. */
    val Upload: ImageVector by lazy {
        glyph(
            "upload",
            s("M12 16 V4.5 M7.5 9 L12 4.5 L16.5 9"),
            s("M5 14 V18.5 A1.5 1.5 0 0 0 6.5 20 H17.5 A1.5 1.5 0 0 0 19 18.5 V14"),
        )
    }

    /** Web `camera`. */
    val Camera: ImageVector by lazy {
        glyph(
            "camera",
            s("M3 8.5 A1.8 1.8 0 0 1 4.8 6.7 H7.5 L9 4.5 H15 L16.5 6.7 H19.2 A1.8 1.8 0 0 1 21 " +
                "8.5 V17.5 A1.8 1.8 0 0 1 19.2 19.3 H4.8 A1.8 1.8 0 0 1 3 17.5 Z"),
            s("M8.6 12.8 A3.4 3.4 0 1 0 15.4 12.8 A3.4 3.4 0 1 0 8.6 12.8 Z"),
        )
    }

    /** Web `microphone-off`. */
    val MicrophoneOff: ImageVector by lazy {
        glyph(
            "microphone-off",
            s("M12 3 H12 A3 3 0 0 1 15 6 V11 A3 3 0 0 1 12 14 H12 A3 3 0 0 1 9 11 V6 A3 3 0 0 1 " +
                "12 3 Z"),
            s("M5.5 11.5 A6.5 6.5 0 0 0 18.5 11.5"),
            s("M12 18 L12 21"),
            s("M8.5 21 L15.5 21"),
            s("M4 3.8 L20 20.2"),
        )
    }

    /** Web `microphone`. */
    val Microphone: ImageVector by lazy {
        glyph(
            "microphone",
            s("M12 3 H12 A3 3 0 0 1 15 6 V11 A3 3 0 0 1 12 14 H12 A3 3 0 0 1 9 11 V6 A3 3 0 0 1 " +
                "12 3 Z"),
            s("M5.5 11.5 A6.5 6.5 0 0 0 18.5 11.5"),
            s("M12 18 L12 21"),
            s("M8.5 21 L15.5 21"),
        )
    }

    /** Web `photo`. */
    val Photo: ImageVector by lazy {
        glyph(
            "photo",
            s("M5.9 4.5 H18.1 A2.4 2.4 0 0 1 20.5 6.9 V17.1 A2.4 2.4 0 0 1 18.1 19.5 H5.9 A2.4 " +
                "2.4 0 0 1 3.5 17.1 V6.9 A2.4 2.4 0 0 1 5.9 4.5 Z"),
            s("M6.7 9.5 A1.8 1.8 0 1 0 10.3 9.5 A1.8 1.8 0 1 0 6.7 9.5 Z"),
            s("M4 17 L9.5 12 L13 15 L16 12.5 L20 16.5"),
        )
    }

    /** Web `player-pause`. */
    val PlayerPause: ImageVector by lazy {
        glyph(
            "player-pause",
            s("M7.5 4.5 H9.1 A1 1 0 0 1 10.1 5.5 V18.5 A1 1 0 0 1 9.1 19.5 H7.5 A1 1 0 0 1 6.5 " +
                "18.5 V5.5 A1 1 0 0 1 7.5 4.5 Z"),
            s("M14.9 4.5 H16.5 A1 1 0 0 1 17.5 5.5 V18.5 A1 1 0 0 1 16.5 19.5 H14.9 A1 1 0 0 1 " +
                "13.9 18.5 V5.5 A1 1 0 0 1 14.9 4.5 Z"),
        )
    }

    /** Web `player-play`. */
    val PlayerPlay: ImageVector by lazy {
        glyph(
            "player-play",
            s("M7.5 6.8 Q7.5 5 9 5.9 L18 11.1 Q19.4 12 18 12.9 L9 18.1 Q7.5 19 7.5 17.2 Z"),
        )
    }

    /** Web `player-skip-back`. */
    val PlayerSkipBack: ImageVector by lazy {
        glyph(
            "player-skip-back",
            s("M18.5 6.8 Q18.5 5 17 5.9 L9.5 11.1 Q8.1 12 9.5 12.9 L17 18.1 Q18.5 19 18.5 17.2 " +
                "Z"),
            s("M6 5.5 L6 18.5"),
        )
    }

    /** Web `player-skip-forward`. */
    val PlayerSkipForward: ImageVector by lazy {
        glyph(
            "player-skip-forward",
            s("M5.5 6.8 Q5.5 5 7 5.9 L14.5 11.1 Q15.9 12 14.5 12.9 L7 18.1 Q5.5 19 5.5 17.2 Z"),
            s("M18 5.5 L18 18.5"),
        )
    }

    /** Web `player-stop`. */
    val PlayerStop: ImageVector by lazy {
        glyph(
            "player-stop",
            s("M7 5 H17 A2 2 0 0 1 19 7 V17 A2 2 0 0 1 17 19 H7 A2 2 0 0 1 5 17 V7 A2 2 0 0 1 7 " +
                "5 Z"),
        )
    }

    /** Web `volume-off`. */
    val VolumeOff: ImageVector by lazy {
        glyph(
            "volume-off",
            s("M4.8 9.5 H7 L11 6.3 Q12 5.5 12 6.8 V17.2 Q12 18.5 11 17.7 L7 14.5 H4.8 Q4 14.5 4 " +
                "13.7 V10.3 Q4 9.5 4.8 9.5 Z"),
            s("M16 9.5 L21 14.5"),
            s("M21 9.5 L16 14.5"),
        )
    }

    /** Web `volume`. */
    val Volume: ImageVector by lazy {
        glyph(
            "volume",
            s("M4.8 9.5 H7 L11 6.3 Q12 5.5 12 6.8 V17.2 Q12 18.5 11 17.7 L7 14.5 H4.8 Q4 14.5 4 " +
                "13.7 V10.3 Q4 9.5 4.8 9.5 Z"),
            s("M15.5 9 A4 4 0 0 1 15.5 15"),
            s("M17.8 6.8 A7.2 7.2 0 0 1 17.8 17.2"),
        )
    }

    /** Web `battery`. */
    val Battery: ImageVector by lazy {
        glyph(
            "battery",
            s("M4.5 7.5 H17.5 A2 2 0 0 1 19.5 9.5 V14.5 A2 2 0 0 1 17.5 16.5 H4.5 A2 2 0 0 1 " +
                "2.5 14.5 V9.5 A2 2 0 0 1 4.5 7.5 Z"),
            s("M21.5 10.5 V13.5"),
            f("M5.4 10 H6.8 A0.6 0.6 0 0 1 7.4 10.6 V13.4 A0.6 0.6 0 0 1 6.8 14 H5.4 A0.6 0.6 0 " +
                "0 1 4.8 13.4 V10.6 A0.6 0.6 0 0 1 5.4 10 Z"),
            f("M9 10 H10.4 A0.6 0.6 0 0 1 11 10.6 V13.4 A0.6 0.6 0 0 1 10.4 14 H9 A0.6 0.6 0 0 " +
                "1 8.4 13.4 V10.6 A0.6 0.6 0 0 1 9 10 Z"),
            f("M12.6 10 H14 A0.6 0.6 0 0 1 14.6 10.6 V13.4 A0.6 0.6 0 0 1 14 14 H12.6 A0.6 0.6 " +
                "0 0 1 12 13.4 V10.6 A0.6 0.6 0 0 1 12.6 10 Z"),
        )
    }

    /** Web `bluetooth`. */
    val Bluetooth: ImageVector by lazy {
        glyph(
            "bluetooth",
            s("M7.5 7.5 L16.5 16.5 L12 21 V3 L16.5 7.5 L7.5 16.5"),
        )
    }

    /** Web `clipboard`. */
    val Clipboard: ImageVector by lazy {
        glyph(
            "clipboard",
            s("M9 4.6 H7 A1.6 1.6 0 0 0 5.4 6.2 V19 A1.6 1.6 0 0 0 7 20.6 H17 A1.6 1.6 0 0 0 " +
                "18.6 19 V6.2 A1.6 1.6 0 0 0 17 4.6 H15"),
            s("M10.1 2.8 H13.9 A1.1 1.1 0 0 1 15 3.9 V5.1 A1.1 1.1 0 0 1 13.9 6.2 H10.1 A1.1 " +
                "1.1 0 0 1 9 5.1 V3.9 A1.1 1.1 0 0 1 10.1 2.8 Z"),
        )
    }

    /** Web `external-link`. */
    val ExternalLink: ImageVector by lazy {
        glyph(
            "external-link",
            s("M14 4 H20 V10"),
            s("M20 4 L11 13"),
            s("M18 13.5 V18.5 A1.5 1.5 0 0 1 16.5 20 H5.5 A1.5 1.5 0 0 1 4 18.5 V7.5 A1.5 1.5 0 " +
                "0 1 5.5 6 H10.5"),
        )
    }

    /** Web `globe`. */
    val Globe: ImageVector by lazy {
        glyph(
            "globe",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M8.2 12 A3.8 9 0 1 0 15.8 12 A3.8 9 0 1 0 8.2 12 Z"),
            s("M3.2 9 L20.8 9"),
            s("M3.2 15 L20.8 15"),
        )
    }

    /** Web `map-pin`. */
    val MapPin: ImageVector by lazy {
        glyph(
            "map-pin",
            s("M12 21 C12 21 5 15 5 9.8 A7 7 0 0 1 19 9.8 C19 15 12 21 12 21 Z"),
            s("M9.4 9.8 A2.6 2.6 0 1 0 14.6 9.8 A2.6 2.6 0 1 0 9.4 9.8 Z"),
        )
    }

    /** Web `moon`. */
    val Moon: ImageVector by lazy {
        glyph(
            "moon",
            s("M20 13.5 A8 8 0 1 1 10.5 4 A6.2 6.2 0 0 0 20 13.5 Z"),
        )
    }

    /** Web `qr-code`. */
    val QrCode: ImageVector by lazy {
        glyph(
            "qr-code",
            s("M4.9 3.5 H8.6 A1.4 1.4 0 0 1 10 4.9 V8.6 A1.4 1.4 0 0 1 8.6 10 H4.9 A1.4 1.4 0 0 " +
                "1 3.5 8.6 V4.9 A1.4 1.4 0 0 1 4.9 3.5 Z"),
            s("M15.4 3.5 H19.1 A1.4 1.4 0 0 1 20.5 4.9 V8.6 A1.4 1.4 0 0 1 19.1 10 H15.4 A1.4 " +
                "1.4 0 0 1 14 8.6 V4.9 A1.4 1.4 0 0 1 15.4 3.5 Z"),
            s("M4.9 14 H8.6 A1.4 1.4 0 0 1 10 15.4 V19.1 A1.4 1.4 0 0 1 8.6 20.5 H4.9 A1.4 1.4 " +
                "0 0 1 3.5 19.1 V15.4 A1.4 1.4 0 0 1 4.9 14 Z"),
            s("M14.6 14 H16.2 A0.6 0.6 0 0 1 16.8 14.6 V16.2 A0.6 0.6 0 0 1 16.2 16.8 H14.6 " +
                "A0.6 0.6 0 0 1 14 16.2 V14.6 A0.6 0.6 0 0 1 14.6 14 Z"),
            s("M18.7 14.4 H20 A0.5 0.5 0 0 1 20.5 14.9 V16.2 A0.5 0.5 0 0 1 20 16.7 H18.7 A0.5 " +
                "0.5 0 0 1 18.2 16.2 V14.9 A0.5 0.5 0 0 1 18.7 14.4 Z"),
            s("M14.9 18.2 H16.2 A0.5 0.5 0 0 1 16.7 18.7 V20 A0.5 0.5 0 0 1 16.2 20.5 H14.9 " +
                "A0.5 0.5 0 0 1 14.4 20 V18.7 A0.5 0.5 0 0 1 14.9 18.2 Z"),
            s("M18.6 18 H19.9 A0.6 0.6 0 0 1 20.5 18.6 V19.9 A0.6 0.6 0 0 1 19.9 20.5 H18.6 " +
                "A0.6 0.6 0 0 1 18 19.9 V18.6 A0.6 0.6 0 0 1 18.6 18 Z"),
        )
    }

    /** Web `share`. */
    val Share: ImageVector by lazy {
        glyph(
            "share",
            s("M3.6 12 A2.4 2.4 0 1 0 8.4 12 A2.4 2.4 0 1 0 3.6 12 Z"),
            s("M15.1 6 A2.4 2.4 0 1 0 19.9 6 A2.4 2.4 0 1 0 15.1 6 Z"),
            s("M15.1 18 A2.4 2.4 0 1 0 19.9 18 A2.4 2.4 0 1 0 15.1 18 Z"),
            s("M8.1 10.9 L15.4 7.1"),
            s("M8.1 13.1 L15.4 16.9"),
        )
    }

    /** Web `sun`. */
    val Sun: ImageVector by lazy {
        glyph(
            "sun",
            s("M8 12 A4 4 0 1 0 16 12 A4 4 0 1 0 8 12 Z"),
            s("M12 2.5 V5 M12 19 V21.5 M21.5 12 H19 M5 12 H2.5 M18.7 5.3 L16.9 7.1 M7.1 16.9 " +
                "L5.3 18.7 M18.7 18.7 L16.9 16.9 M7.1 7.1 L5.3 5.3"),
        )
    }

    /** Web `wifi`. */
    val Wifi: ImageVector by lazy {
        glyph(
            "wifi",
            s("M3 8.5 A13 13 0 0 1 21 8.5"),
            s("M6 12 A8.5 8.5 0 0 1 18 12"),
            s("M9 15.5 A4 4 0 0 1 15 15.5"),
            f("M11.4 19 A0.6 0.6 0 1 0 12.6 19 A0.6 0.6 0 1 0 11.4 19 Z"),
        )
    }

    /** Web `account-hub`. */
    val AccountHub: ImageVector by lazy {
        glyph(
            "account-hub",
            s("M7.7 8.2 A2.7 2.7 0 1 0 13.1 8.2 A2.7 2.7 0 1 0 7.7 8.2 Z"),
            s("M5.4 17.6 C6.1 14.6 8 13.3 10.4 13.3 C11.3 13.3 12.1 13.5 12.8 13.9"),
            s("M13 15.8 A4 4 0 1 0 21 15.8 A4 4 0 1 0 13 15.8 Z"),
            s("M17 13.6 V18"),
            s("M17.9 14.6 C17.2 14.1 15.6 14.1 15.6 15.2 C15.6 16.3 18.4 15.9 18.4 17 C18.4 " +
                "18.1 16.6 18.1 15.9 17.6"),
            s("M17 11.8 A4 4 0 0 1 21 15.8"),
        )
    }

    /** Web `allowances-rentals`. */
    val AllowancesRentals: ImageVector by lazy {
        glyph(
            "allowances-rentals",
            s("M12 2.8 L20.5 7 V17 L12 21.2 L3.5 17 V7 Z"),
            s("M3.5 7 L12 11.2 L20.5 7"),
            s("M12 11.2 V21.2"),
            s("M7.75 4.9 L16.25 9.1"),
        )
    }

    /** Web `card-expense`. */
    val CardExpense: ImageVector by lazy {
        glyph(
            "card-expense",
            s("M4.9 5.5 H19.1 A2.4 2.4 0 0 1 21.5 7.9 V16.1 A2.4 2.4 0 0 1 19.1 18.5 H4.9 A2.4 " +
                "2.4 0 0 1 2.5 16.1 V7.9 A2.4 2.4 0 0 1 4.9 5.5 Z"),
            s("M2.5 9 L21.5 9"),
            s("M5.8 11.4 H8.1 A0.7 0.7 0 0 1 8.8 12.1 V13.7 A0.7 0.7 0 0 1 8.1 14.4 H5.8 A0.7 " +
                "0.7 0 0 1 5.1 13.7 V12.1 A0.7 0.7 0 0 1 5.8 11.4 Z"),
            s("M11.2 15.4 L18.5 15.4"),
        )
    }

    /** Web `cash-expense`. */
    val CashExpense: ImageVector by lazy {
        glyph(
            "cash-expense",
            s("M4 5.5 H20 A2 2 0 0 1 22 7.5 V16.5 A2 2 0 0 1 20 18.5 H4 A2 2 0 0 1 2 16.5 V7.5 " +
                "A2 2 0 0 1 4 5.5 Z"),
            s("M12 8.4 V15.6"),
            s("M14.1 9.8 C13.2 9.2 10.3 9.2 10.3 10.8 C10.3 12.4 13.7 11.7 13.7 13.3 C13.7 14.9 " +
                "10.8 14.9 9.9 14.3"),
            s("M4.15 8.1 A0.75 0.75 0 1 0 5.65 8.1 A0.75 0.75 0 1 0 4.15 8.1 Z"),
            s("M18.35 15.9 A0.75 0.75 0 1 0 19.85 15.9 A0.75 0.75 0 1 0 18.35 15.9 Z"),
        )
    }

    /** Web `chart-of-accounts`. */
    val ChartOfAccounts: ImageVector by lazy {
        glyph(
            "chart-of-accounts",
            s("M3.8 5.2 A1.2 1.2 0 1 0 6.2 5.2 A1.2 1.2 0 1 0 3.8 5.2 Z"),
            s("M3.8 9.8 A1.2 1.2 0 1 0 6.2 9.8 A1.2 1.2 0 1 0 3.8 9.8 Z"),
            s("M7 14.4 A1.2 1.2 0 1 0 9.4 14.4 A1.2 1.2 0 1 0 7 14.4 Z"),
            s("M7 19 A1.2 1.2 0 1 0 9.4 19 A1.2 1.2 0 1 0 7 19 Z"),
            s("M8.4 5.2 L20 5.2"),
            s("M8.4 9.8 L20 9.8"),
            s("M11.6 14.4 L20 14.4"),
            s("M11.6 19 L20 19"),
        )
    }

    /** Web `cost-report`. */
    val CostReport: ImageVector by lazy {
        glyph(
            "cost-report",
            s("M6.2 2.6 H17.8 A2.2 2.2 0 0 1 20 4.8 V19.2 A2.2 2.2 0 0 1 17.8 21.4 H6.2 A2.2 " +
                "2.2 0 0 1 4 19.2 V4.8 A2.2 2.2 0 0 1 6.2 2.6 Z"),
            s("M7.4 14.6 L10 12 L12.4 13.3 L16.6 8.6"),
            s("M16.1 8.6 A0.5 0.5 0 1 0 17.1 8.6 A0.5 0.5 0 1 0 16.1 8.6 Z"),
            s("M7.6 17.8 L14.4 17.8"),
        )
    }

    /** Web `dashboard`. */
    val Dashboard: ImageVector by lazy {
        glyph(
            "dashboard",
            s("M4.8 3 H8.8 A1.8 1.8 0 0 1 10.6 4.8 V9.6 A1.8 1.8 0 0 1 8.8 11.4 H4.8 A1.8 1.8 0 " +
                "0 1 3 9.6 V4.8 A1.8 1.8 0 0 1 4.8 3 Z"),
            s("M15.2 3 H19.2 A1.8 1.8 0 0 1 21 4.8 V6.4 A1.8 1.8 0 0 1 19.2 8.2 H15.2 A1.8 1.8 " +
                "0 0 1 13.4 6.4 V4.8 A1.8 1.8 0 0 1 15.2 3 Z"),
            s("M15.2 11.2 H19.2 A1.8 1.8 0 0 1 21 13 V19.2 A1.8 1.8 0 0 1 19.2 21 H15.2 A1.8 " +
                "1.8 0 0 1 13.4 19.2 V13 A1.8 1.8 0 0 1 15.2 11.2 Z"),
            s("M4.8 14.2 H8.8 A1.8 1.8 0 0 1 10.6 16 V19.2 A1.8 1.8 0 0 1 8.8 21 H4.8 A1.8 1.8 " +
                "0 0 1 3 19.2 V16 A1.8 1.8 0 0 1 4.8 14.2 Z"),
        )
    }

    /** Web `deal-memo`. */
    val DealMemo: ImageVector by lazy {
        glyph(
            "deal-memo",
            s("M6 2.6 H13.4 L18.2 7.4 V19.8 A1.4 1.4 0 0 1 16.8 21.2 H7.4 A1.4 1.4 0 0 1 6 19.8 " +
                "V4 A1.4 1.4 0 0 1 7.4 2.6 Z"),
            s("M13.2 2.7 V7.5 H18"),
            s("M8.3 10.4 L15.6 10.4"),
            s("M8.3 12.5 L15.6 12.5"),
            s("M8.3 14.6 L12.4 14.6"),
            s("M11.8 17 A1.9 1.9 0 1 0 15.6 17 A1.9 1.9 0 1 0 11.8 17 Z"),
            s("M12.3 18.3 L11.7 20.6 L13.7 19.4 L15.7 20.6 L15.1 18.3"),
        )
    }

    /** Web `invoice`. */
    val Invoice: ImageVector by lazy {
        glyph(
            "invoice",
            s("M5.5 2.8 H15 L18.5 6.3 V19.6 A1.6 1.6 0 0 1 16.9 21.2 H7.1 A1.6 1.6 0 0 1 5.5 " +
                "19.6 Z"),
            s("M14.6 2.9 V6.6 H18.4"),
            s("M8.4 11 L15.6 11"),
            s("M8.4 13.4 L13.4 13.4"),
            s("M13 16 V18.6 M14.4 16.5 C13.9 16.2 11.9 16.2 11.9 17.2 C11.9 18.1 14.1 17.8 14.1 " +
                "18.7 C14.1 19.6 12.1 19.6 11.6 19.2"),
        )
    }

    /** Web `payroll`. */
    val Payroll: ImageVector by lazy {
        glyph(
            "payroll",
            s("M3.8 6 H20.2 A1.3 1.3 0 0 1 21.5 7.3 V13.3 A1.3 1.3 0 0 1 20.2 14.6 H3.8 A1.3 " +
                "1.3 0 0 1 2.5 13.3 V7.3 A1.3 1.3 0 0 1 3.8 6 Z"),
            s("M9.3 6 L9.3 14.6"),
            s("M14.7 6 L14.7 14.6"),
            s("M12 8 V12.6"),
            s("M13.3 8.9 C12.8 8.5 11 8.5 11 9.5 C11 10.5 13 10.2 13 11.2 C13 12.2 11.2 12.2 " +
                "10.7 11.8"),
            s("M4.3 16.5 L19.7 16.5"),
            s("M5.9 18.4 L18.1 18.4"),
        )
    }

    /** Web `purchase-order`. */
    val PurchaseOrder: ImageVector by lazy {
        glyph(
            "purchase-order",
            s("M6 3.8 H18 A2 2 0 0 1 20 5.8 V19.2 A2 2 0 0 1 18 21.2 H6 A2 2 0 0 1 4 19.2 V5.8 " +
                "A2 2 0 0 1 6 3.8 Z"),
            s("M10.1 2.2 H13.9 A1.1 1.1 0 0 1 15 3.3 V4.2 A1.1 1.1 0 0 1 13.9 5.3 H10.1 A1.1 " +
                "1.1 0 0 1 9 4.2 V3.3 A1.1 1.1 0 0 1 10.1 2.2 Z"),
            s("M7.5 11.4 l1.4 1.4 l2.6 -2.9"),
            s("M13.4 11.3 L16.5 11.3"),
            s("M7.6 15.2 L16.4 15.2"),
            s("M7.6 17.8 L13 17.8"),
        )
    }

    /** Web `reports`. */
    val Reports: ImageVector by lazy {
        glyph(
            "reports",
            s("M4 20 L20.5 20"),
            s("M6.7 11 H8.3 A0.7 0.7 0 0 1 9 11.7 V17.3 A0.7 0.7 0 0 1 8.3 18 H6.7 A0.7 0.7 0 0 " +
                "1 6 17.3 V11.7 A0.7 0.7 0 0 1 6.7 11 Z"),
            s("M11.2 6.5 H12.8 A0.7 0.7 0 0 1 13.5 7.2 V17.3 A0.7 0.7 0 0 1 12.8 18 H11.2 A0.7 " +
                "0.7 0 0 1 10.5 17.3 V7.2 A0.7 0.7 0 0 1 11.2 6.5 Z"),
            s("M15.7 13 H17.3 A0.7 0.7 0 0 1 18 13.7 V17.3 A0.7 0.7 0 0 1 17.3 18 H15.7 A0.7 " +
                "0.7 0 0 1 15 17.3 V13.7 A0.7 0.7 0 0 1 15.7 13 Z"),
            s("M4 4 L4 20"),
        )
    }

    /** Web `review-inbox`. */
    val ReviewInbox: ImageVector by lazy {
        glyph(
            "review-inbox",
            s("M3.4 13.8 L6.4 5.2 H17.6 L20.6 13.8"),
            s("M3.4 13.8 V18.4 A1.4 1.4 0 0 0 4.8 19.8 H19.2 A1.4 1.4 0 0 0 20.6 18.4 V13.8 " +
                "H15.4 L14 16.2 H10 L8.6 13.8 Z"),
        )
    }

    /** Web `timecard`. */
    val Timecard: ImageVector by lazy {
        glyph(
            "timecard",
            s("M6.4 2.4 H17.6 A2.4 2.4 0 0 1 20 4.8 V13.6 A2.4 2.4 0 0 1 17.6 16 H6.4 A2.4 2.4 " +
                "0 0 1 4 13.6 V4.8 A2.4 2.4 0 0 1 6.4 2.4 Z"),
            s("M8 8.4 A4 4 0 1 0 16 8.4 A4 4 0 1 0 8 8.4 Z"),
            s("M12 5.7 V8.4 L13.9 9.6"),
            s("M7.65 13.3 H16.35 A0.85 0.85 0 0 1 17.2 14.15 V14.15 A0.85 0.85 0 0 1 16.35 15 " +
                "H7.65 A0.85 0.85 0 0 1 6.8 14.15 V14.15 A0.85 0.85 0 0 1 7.65 13.3 Z"),
            s("M9.2 15.4 H14.8 A0.8 0.8 0 0 1 15.6 16.2 V20.4 A0.8 0.8 0 0 1 14.8 21.2 H9.2 " +
                "A0.8 0.8 0 0 1 8.4 20.4 V16.2 A0.8 0.8 0 0 1 9.2 15.4 Z"),
            s("M10.2 18.4 L13.8 18.4"),
        )
    }

    /** Web `vendor`. */
    val Vendor: ImageVector by lazy {
        glyph(
            "vendor",
            s("M3.6 8.6 L5.1 4.4 H18.9 L20.4 8.6"),
            s("M4.6 8.6 V20.4 H19.4 V8.6"),
            s("M3.6 8.6 Q5.8 11.2 8 8.6 Q10.2 11.2 12 8.6 Q13.8 11.2 16 8.6 Q18.2 11.2 20.4 8.6"),
            s("M9.6 14.4 H14.4 V20.4 H9.6 Z"),
        )
    }

    /** Web `bank-card`. */
    val BankCard: ImageVector by lazy {
        glyph(
            "bank-card",
            s("M5.2 5 H18.8 A2.6 2.6 0 0 1 21.4 7.6 V16.4 A2.6 2.6 0 0 1 18.8 19 H5.2 A2.6 2.6 " +
                "0 0 1 2.6 16.4 V7.6 A2.6 2.6 0 0 1 5.2 5 Z"),
            s("M2.6 9.2 H21.4"),
            s("M6.1 12.4 H8.7 A0.7 0.7 0 0 1 9.4 13.1 V14.9 A0.7 0.7 0 0 1 8.7 15.6 H6.1 A0.7 " +
                "0.7 0 0 1 5.4 14.9 V13.1 A0.7 0.7 0 0 1 6.1 12.4 Z"),
            s("M12 15.6 L18.4 15.6"),
        )
    }

    /** Web `bank`. */
    val Bank: ImageVector by lazy {
        glyph(
            "bank",
            s("M12 3.2 L21 7.4 H3 Z"),
            s("M3 19.8 L21 19.8"),
            s("M5.2 10.4 L5.2 17"),
            s("M9.7 10.4 L9.7 17"),
            s("M14.3 10.4 L14.3 17"),
            s("M18.8 10.4 L18.8 17"),
        )
    }

    /** Web `coins`. */
    val Coins: ImageVector by lazy {
        glyph(
            "coins",
            s("M3 6.4 A5.5 2.4 0 1 0 14 6.4 A5.5 2.4 0 1 0 3 6.4 Z"),
            s("M3 6.4 V11 C3 12.3 5 13.3 7.4 13.5"),
            s("M14 11 V6.4"),
            s("M9.5 13.6 A5.5 2.4 0 1 0 20.5 13.6 A5.5 2.4 0 1 0 9.5 13.6 Z"),
            s("M9.5 13.6 V18.2 C9.5 19.5 12 20.6 15 20.6 C18 20.6 20.5 19.5 20.5 18.2 V13.6"),
        )
    }

    /** Web `currency`. */
    val Currency: ImageVector by lazy {
        glyph(
            "currency",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M12 6.4 V17.6"),
            s("M14.7 8.8 C13.7 7.8 9.4 7.8 9.4 10.3 C9.4 12.8 14.7 11.7 14.7 14.2 C14.7 16.7 " +
                "10.3 16.7 9.3 15.6"),
        )
    }

    /** Web `ledger`. */
    val Ledger: ImageVector by lazy {
        glyph(
            "ledger",
            s("M12 5.6 C10 4.2 6.2 4.2 4 4.8 V18.6 C6.2 18 10 18 12 19.4 C14 18 17.8 18 20 18.6 " +
                "V4.8 C17.8 4.2 14 4.2 12 5.6 Z"),
            s("M12 5.6 V19.4"),
            s("M6.4 8.6 H9.6 M6.4 11 H9.6 M14.4 8.6 H17.6 M14.4 11 H17.6"),
        )
    }

    /** Web `meal-break`. */
    val MealBreak: ImageVector by lazy {
        glyph(
            "meal-break",
            s("M8 3 V21"),
            s("M5.6 3 V7 A2.4 2.4 0 0 0 10.4 7 V3"),
            s("M16 21 V13 H14.4 C14.4 8 16 3 16 3 C16 3 16 8 16 13"),
            s("M16 3 V13"),
        )
    }

    /** Web `mileage`. */
    val Mileage: ImageVector by lazy {
        glyph(
            "mileage",
            s("M4.4 14 L6.1 9.2 C6.4 8.4 7.1 7.9 7.9 7.9 H16.1 C16.9 7.9 17.6 8.4 17.9 9.2 " +
                "L19.6 14"),
            s("M3 14 H21 V16.8 A1 1 0 0 1 20 17.8 H18.6 A1 1 0 0 1 17.6 16.8 V15.6 H6.4 V16.8 " +
                "A1 1 0 0 1 5.4 17.8 H4 A1 1 0 0 1 3 16.8 Z"),
            s("M7.2 15.6 A0 0 0 1 0 7.2 15.6 A0 0 0 1 0 7.2 15.6 Z"),
            s("M6.4 11.6 L17.6 11.6"),
        )
    }

    /** Web `per-diem`. */
    val PerDiem: ImageVector by lazy {
        glyph(
            "per-diem",
            s("M5.2 6 H18.8 A2.2 2.2 0 0 1 21 8.2 V15.8 A2.2 2.2 0 0 1 18.8 18 H5.2 A2.2 2.2 0 " +
                "0 1 3 15.8 V8.2 A2.2 2.2 0 0 1 5.2 6 Z"),
            s("M3.6 7 L12 13 L20.4 7"),
            s("M12 13 V15 M13.4 13.4 C12.9 13.1 11 13.1 11 14 C11 14.8 13 14.6 13 15.4 C13 16.3 " +
                "11.1 16.3 10.6 15.9"),
        )
    }

    /** Web `receipt`. */
    val Receipt: ImageVector by lazy {
        glyph(
            "receipt",
            s("M5.5 2.8 H18.5 V20.6 L16.4 19.4 L14.3 20.6 L12 19.4 L9.7 20.6 L7.6 19.4 L5.5 " +
                "20.6 Z"),
            s("M8 7.4 L16 7.4"),
            s("M8 10.4 L16 10.4"),
            s("M8 13.4 L12.6 13.4"),
        )
    }

    /** Web `refund`. */
    val Refund: ImageVector by lazy {
        glyph(
            "refund",
            s("M5.2 9.2 A7.6 7.6 0 1 1 4.4 14.2"),
            s("M5.2 5.6 V9.2 H8.8"),
            s("M12 8.8 V15.6"),
            s("M14 10 C13.3 9.5 10.4 9.5 10.4 11 C10.4 12.5 13.6 11.8 13.6 13.3 C13.6 14.8 10.7 " +
                "14.8 10 14.3"),
        )
    }

    /** Web `tax`. */
    val Tax: ImageVector by lazy {
        glyph(
            "tax",
            s("M3 12 A9 9 0 1 0 21 12 A9 9 0 1 0 3 12 Z"),
            s("M7.7 9.2 A1.5 1.5 0 1 0 10.7 9.2 A1.5 1.5 0 1 0 7.7 9.2 Z"),
            s("M13.3 14.8 A1.5 1.5 0 1 0 16.3 14.8 A1.5 1.5 0 1 0 13.3 14.8 Z"),
            s("M15.4 8.6 L8.6 15.4"),
        )
    }

    /** Web `wallet`. */
    val Wallet: ImageVector by lazy {
        glyph(
            "wallet",
            s("M5.6 5.6 H18.4 A2.6 2.6 0 0 1 21 8.2 V16.2 A2.6 2.6 0 0 1 18.4 18.8 H5.6 A2.6 " +
                "2.6 0 0 1 3 16.2 V8.2 A2.6 2.6 0 0 1 5.6 5.6 Z"),
            s("M15.6 10.8 H21 V14.2 H15.6 A1.7 1.7 0 0 1 15.6 10.8 Z"),
            s("M16.85 12.5 A0.55 0.55 0 1 0 17.95 12.5 A0.55 0.55 0 1 0 16.85 12.5 Z"),
            s("M3 8.8 H15"),
        )
    }

    /** Web `arrow-left`. */
    val ArrowLeft: ImageVector by lazy {
        glyph(
            "arrow-left",
            s("M20 12 L5 12"),
            s("M11 6 L5 12 L11 18"),
        )
    }

    /** Web `arrow-right`. */
    val ArrowRight: ImageVector by lazy {
        glyph(
            "arrow-right",
            s("M4 12 L19 12"),
            s("M13 6 L19 12 L13 18"),
        )
    }

    /** Web `chevron-down`. */
    val ChevronDown: ImageVector by lazy {
        glyph(
            "chevron-down",
            s("M5 9 L12 16 L19 9"),
        )
    }

    /** Web `chevron-left`. */
    val ChevronLeft: ImageVector by lazy {
        glyph(
            "chevron-left",
            s("M15 5 L8 12 L15 19"),
        )
    }

    /** Web `chevron-right`. */
    val ChevronRight: ImageVector by lazy {
        glyph(
            "chevron-right",
            s("M9 5 L16 12 L9 19"),
        )
    }

    /** Web `chevron-up`. */
    val ChevronUp: ImageVector by lazy {
        glyph(
            "chevron-up",
            s("M5 15 L12 8 L19 15"),
        )
    }

    /** Web `dots-horizontal`. */
    val DotsHorizontal: ImageVector by lazy {
        glyph(
            "dots-horizontal",
            s("M3.65 12 A1.35 1.35 0 1 0 6.35 12 A1.35 1.35 0 1 0 3.65 12 Z"),
            s("M10.65 12 A1.35 1.35 0 1 0 13.35 12 A1.35 1.35 0 1 0 10.65 12 Z"),
            s("M17.65 12 A1.35 1.35 0 1 0 20.35 12 A1.35 1.35 0 1 0 17.65 12 Z"),
        )
    }

    /** Web `dots-vertical`. */
    val DotsVertical: ImageVector by lazy {
        glyph(
            "dots-vertical",
            s("M10.65 5 A1.35 1.35 0 1 0 13.35 5 A1.35 1.35 0 1 0 10.65 5 Z"),
            s("M10.65 12 A1.35 1.35 0 1 0 13.35 12 A1.35 1.35 0 1 0 10.65 12 Z"),
            s("M10.65 19 A1.35 1.35 0 1 0 13.35 19 A1.35 1.35 0 1 0 10.65 19 Z"),
        )
    }

    /** Web `home`. */
    val Home: ImageVector by lazy {
        glyph(
            "home",
            s("M3.5 11 L12 4 L20.5 11"),
            s("M5.6 9.3 V19.4 A0.9 0.9 0 0 0 6.5 20.3 H17.5 A0.9 0.9 0 0 0 18.4 19.4 V9.3"),
            s("M9.6 20.3 V14 H14.4 V20.3"),
        )
    }

    /** Web `menu`. */
    val Menu: ImageVector by lazy {
        glyph(
            "menu",
            s("M4 7 L20 7"),
            s("M4 12 L20 12"),
            s("M4 17 L20 17"),
        )
    }

    /** Web `approver`. */
    val Approver: ImageVector by lazy {
        glyph(
            "approver",
            s("M6.2 8 A3.2 3.2 0 1 0 12.6 8 A3.2 3.2 0 1 0 6.2 8 Z"),
            s("M3.8 19 C4.7 15.4 6.9 13.8 9.4 13.8 C10.4 13.8 11.4 14 12.2 14.5"),
            s("M14.4 17.4 L16.4 19.4 L20.2 15.2"),
        )
    }

    /** Web `crew`. */
    val Crew: ImageVector by lazy {
        glyph(
            "crew",
            s("M5.8 8.6 A3.2 3.2 0 1 0 12.2 8.6 A3.2 3.2 0 1 0 5.8 8.6 Z"),
            s("M3.6 18.4 C4.4 15 6.5 13.4 9 13.4 C11.5 13.4 13.6 15 14.4 18.4"),
            s("M14.6 7.6 A2.4 2.4 0 1 0 19.4 7.6 A2.4 2.4 0 1 0 14.6 7.6 Z"),
            s("M15.6 13.5 C16 13.4 16.5 13.4 17 13.4 C19.3 13.4 21.1 14.9 21.7 17.6"),
        )
    }

    /** Web `department`. */
    val Department: ImageVector by lazy {
        glyph(
            "department",
            s("M10.1 2.8 H13.9 A1.1 1.1 0 0 1 15 3.9 V6.3 A1.1 1.1 0 0 1 13.9 7.4 H10.1 A1.1 " +
                "1.1 0 0 1 9 6.3 V3.9 A1.1 1.1 0 0 1 10.1 2.8 Z"),
            s("M3.9 16.6 H7.7 A1.1 1.1 0 0 1 8.8 17.7 V20.1 A1.1 1.1 0 0 1 7.7 21.2 H3.9 A1.1 " +
                "1.1 0 0 1 2.8 20.1 V17.7 A1.1 1.1 0 0 1 3.9 16.6 Z"),
            s("M16.3 16.6 H20.1 A1.1 1.1 0 0 1 21.2 17.7 V20.1 A1.1 1.1 0 0 1 20.1 21.2 H16.3 " +
                "A1.1 1.1 0 0 1 15.2 20.1 V17.7 A1.1 1.1 0 0 1 16.3 16.6 Z"),
            s("M12 7.4 V11 M5.8 16.6 V13 H18.2 V16.6"),
        )
    }

    /** Web `onboard`. */
    val Onboard: ImageVector by lazy {
        glyph(
            "onboard",
            s("M6.2 8 A3.2 3.2 0 1 0 12.6 8 A3.2 3.2 0 1 0 6.2 8 Z"),
            s("M3.8 19 C4.7 15.4 6.9 13.8 9.4 13.8 C10.4 13.8 11.4 14 12.2 14.5"),
            s("M17.5 14.5 L17.5 20.5"),
            s("M14.5 17.5 L20.5 17.5"),
        )
    }

    /** Web `person`. */
    val Person: ImageVector by lazy {
        glyph(
            "person",
            s("M8.6 8 A3.4 3.4 0 1 0 15.4 8 A3.4 3.4 0 1 0 8.6 8 Z"),
            s("M5.6 19.4 C6.6 15.5 9 13.8 12 13.8 C15 13.8 17.4 15.5 18.4 19.4"),
        )
    }

    /** Web `producer`. */
    val Producer: ImageVector by lazy {
        glyph(
            "producer",
            s("M4.6 9.2 H13.4 A1.6 1.6 0 0 1 15 10.8 V16.6 A1.6 1.6 0 0 1 13.4 18.2 H4.6 A1.6 " +
                "1.6 0 0 1 3 16.6 V10.8 A1.6 1.6 0 0 1 4.6 9.2 Z"),
            s("M4.4 6.2 A2.2 2.2 0 1 0 8.8 6.2 A2.2 2.2 0 1 0 4.4 6.2 Z"),
            s("M9 6.2 A2.2 2.2 0 1 0 13.4 6.2 A2.2 2.2 0 1 0 9 6.2 Z"),
            s("M15 12 L20.5 9.4 V18 L15 15.4 Z"),
        )
    }

    /** Web `signature`. */
    val Signature: ImageVector by lazy {
        glyph(
            "signature",
            s("M3.5 20.2 L20.5 20.2"),
            s("M4 17 C6 17 6.4 8.8 9 8.8 C10.7 8.8 9.4 15.2 11.4 15.2 C13.2 15.2 13.6 11 16 11 " +
                "C17.4 11 17.1 13.4 19 12.4"),
        )
    }

    /** Web `talent`. */
    val Talent: ImageVector by lazy {
        glyph(
            "talent",
            s("M8.8 7.4 A3.2 3.2 0 1 0 15.2 7.4 A3.2 3.2 0 1 0 8.8 7.4 Z"),
            s("M6.2 19 C7.1 15.5 9.3 13.9 12 13.9 C14.7 13.9 16.9 15.5 17.8 19"),
            s("M19 3 L19.7 4.7 L21.5 4.9 L20.2 6.1 L20.5 7.9 L19 7 L17.5 7.9 L17.8 6.1 L16.5 " +
                "4.9 L18.3 4.7 Z"),
        )
    }

    private val byName: Map<String, () -> ImageVector> = mapOf(
        "check" to { Check },
        "copy" to { Copy },
        "cut" to { Cut },
        "edit" to { Edit },
        "filter" to { Filter },
        "minus" to { Minus },
        "paste" to { Paste },
        "plus" to { Plus },
        "redo" to { Redo },
        "refresh" to { Refresh },
        "search" to { Search },
        "sort-ascending" to { SortAscending },
        "sort-descending" to { SortDescending },
        "trash" to { Trash },
        "undo" to { Undo },
        "x" to { X },
        "fingerprint" to { Fingerprint },
        "key" to { Key },
        "lock-open" to { LockOpen },
        "lock" to { Lock },
        "login" to { Login },
        "logout" to { Logout },
        "shield" to { Shield },
        "user-minus" to { UserMinus },
        "user-plus" to { UserPlus },
        "user" to { User },
        "users" to { Users },
        "at" to { At },
        "bell-off" to { BellOff },
        "bell" to { Bell },
        "link" to { Link },
        "mail" to { Mail },
        "message-circle" to { MessageCircle },
        "message" to { Message },
        "phone" to { Phone },
        "send" to { Send },
        "video" to { Video },
        "alert-circle" to { AlertCircle },
        "alert-triangle" to { AlertTriangle },
        "columns" to { Columns },
        "eye-off" to { EyeOff },
        "eye" to { Eye },
        "grid" to { Grid },
        "help-circle" to { HelpCircle },
        "info" to { Info },
        "layout" to { Layout },
        "list" to { List },
        "maximize" to { Maximize },
        "minimize" to { Minimize },
        "settings" to { Settings },
        "sliders" to { Sliders },
        "toggle-left" to { ToggleLeft },
        "toggle-right" to { ToggleRight },
        "archive" to { Archive },
        "attachment" to { Attachment },
        "calendar" to { Calendar },
        "clock" to { Clock },
        "document" to { Document },
        "folder" to { Folder },
        "form" to { Form },
        "note" to { Note },
        "pdf-export" to { PdfExport },
        "stamp" to { Stamp },
        "badge" to { Badge },
        "bookmark" to { Bookmark },
        "check-circle" to { CheckCircle },
        "flag" to { Flag },
        "heart" to { Heart },
        "star" to { Star },
        "tag" to { Tag },
        "x-circle" to { XCircle },
        "cloud-download" to { CloudDownload },
        "cloud-upload" to { CloudUpload },
        "database" to { Database },
        "download" to { Download },
        "file-minus" to { FileMinus },
        "file-plus" to { FilePlus },
        "file" to { File },
        "folder-open" to { FolderOpen },
        "upload" to { Upload },
        "camera" to { Camera },
        "microphone-off" to { MicrophoneOff },
        "microphone" to { Microphone },
        "photo" to { Photo },
        "player-pause" to { PlayerPause },
        "player-play" to { PlayerPlay },
        "player-skip-back" to { PlayerSkipBack },
        "player-skip-forward" to { PlayerSkipForward },
        "player-stop" to { PlayerStop },
        "volume-off" to { VolumeOff },
        "volume" to { Volume },
        "battery" to { Battery },
        "bluetooth" to { Bluetooth },
        "clipboard" to { Clipboard },
        "external-link" to { ExternalLink },
        "globe" to { Globe },
        "map-pin" to { MapPin },
        "moon" to { Moon },
        "qr-code" to { QrCode },
        "share" to { Share },
        "sun" to { Sun },
        "wifi" to { Wifi },
        "account-hub" to { AccountHub },
        "allowances-rentals" to { AllowancesRentals },
        "card-expense" to { CardExpense },
        "cash-expense" to { CashExpense },
        "chart-of-accounts" to { ChartOfAccounts },
        "cost-report" to { CostReport },
        "dashboard" to { Dashboard },
        "deal-memo" to { DealMemo },
        "invoice" to { Invoice },
        "payroll" to { Payroll },
        "purchase-order" to { PurchaseOrder },
        "reports" to { Reports },
        "review-inbox" to { ReviewInbox },
        "timecard" to { Timecard },
        "vendor" to { Vendor },
        "bank-card" to { BankCard },
        "bank" to { Bank },
        "coins" to { Coins },
        "currency" to { Currency },
        "ledger" to { Ledger },
        "meal-break" to { MealBreak },
        "mileage" to { Mileage },
        "per-diem" to { PerDiem },
        "receipt" to { Receipt },
        "refund" to { Refund },
        "tax" to { Tax },
        "wallet" to { Wallet },
        "arrow-left" to { ArrowLeft },
        "arrow-right" to { ArrowRight },
        "chevron-down" to { ChevronDown },
        "chevron-left" to { ChevronLeft },
        "chevron-right" to { ChevronRight },
        "chevron-up" to { ChevronUp },
        "dots-horizontal" to { DotsHorizontal },
        "dots-vertical" to { DotsVertical },
        "home" to { Home },
        "menu" to { Menu },
        "approver" to { Approver },
        "crew" to { Crew },
        "department" to { Department },
        "onboard" to { Onboard },
        "person" to { Person },
        "producer" to { Producer },
        "signature" to { Signature },
        "talent" to { Talent },
    )

    /** A glyph by its web name (`"purchase-order"`), for callers that hold the name as data. */
    fun named(name: String): ImageVector? = byName[name]?.invoke()
}

private class GlyphPart(val pathData: String, val filled: Boolean)

private fun s(pathData: String) = GlyphPart(pathData, filled = false)

private fun f(pathData: String) = GlyphPart(pathData, filled = true)

private const val VIEWPORT = 24f

/** The bundle's default stroke (`ahIcon`'s `w`), not the 1.25 the source SVGs carry. */
private const val STROKE = 1.5f

private fun glyph(name: String, vararg parts: GlyphPart): ImageVector =
    ImageVector.Builder(
        name = "Ah.$name",
        defaultWidth = VIEWPORT.dp,
        defaultHeight = VIEWPORT.dp,
        viewportWidth = VIEWPORT,
        viewportHeight = VIEWPORT,
    ).apply {
        parts.forEach { part ->
            addPath(
                pathData = addPathNodes(part.pathData),
                fill = if (part.filled) SolidColor(Color.Black) else null,
                stroke = if (part.filled) null else SolidColor(Color.Black),
                strokeLineWidth = if (part.filled) 0f else STROKE,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }.build()
