package com.zillit.desktop.feature.boxschedule.domain

import com.zillit.desktop.core.strings.S
import com.zillit.desktop.core.strings.str
import kotlinx.datetime.LocalDate
import kotlinx.datetime.TimeZone

/** The diary as plain text and as a printable page — the web's Share and Print Selected. */
object DiaryExports {

    /**
     * `ShareScheduleModal.handleCopyAsText` — a fixed-width table to paste into
     * an email, numbered per type exactly as the list numbers it.
     */
    fun scheduleText(rows: List<ScheduleDayRow>, today: LocalDate, zone: TimeZone): String = buildString {
        append("PRODUCTION SCHEDULE\nPrepared: ${DiaryFormat.fullDate(today)}\n\n")
        append("DAY  |  DATE           |  TYPE       |  DETAILS\n")
        append("-----+------------------+-------------+------------------\n")
        rows.forEach { row ->
            val number = if (row.block.isDayOff) "  —" else row.dayNumber.toString().padStart(NUMBER_WIDTH)
            val date = DiaryFormat.listDate(row.date, zone).padEnd(DATE_WIDTH)
            val type = (if (row.block.isDayOff) str(S.desktop_bs_day_off_upper) else row.block.typeName.uppercase())
                .padEnd(TYPE_WIDTH)
            append(" $number  |  $date|  $type  |  ${row.block.title}\n")
        }
        append("\n---\nGenerated by Zillit — ${DiaryFormat.fullDate(today)}")
    }

    /**
     * `PrintableSchedule` as a page that prints itself on load — every chosen
     * day with its events and notes. A day's entries are the ones filed on
     * that block for that date, the same set the day's own detail shows.
     */
    fun printableHtml(
        rows: List<ScheduleDayRow>,
        types: List<ScheduleType>,
        events: List<DiaryEvent>,
        includePersonalNotes: Boolean,
        now: Long,
        zone: TimeZone,
    ): String = buildString {
        val today = DiaryCalendar.dateOf(now, zone)
        append("<!doctype html><html><head><meta charset=\"utf-8\"><title>Production Diary/Box Schedule</title>")
        append("<style>").append(PRINT_CSS).append("</style></head><body>")
        append("<header><h1>Production Diary/Box Schedule</h1>")
        append("<p>Printed: ${DiaryFormat.fullDate(today)} — ${DiaryFormat.time(now, zone)}</p></header>")
        append("<div class=\"legend\">")
        types.forEach { type ->
            append("<span><i style=\"background:${type.color.cssColor()}\"></i>${type.title.escaped()}</span>")
        }
        append("</div>")
        rows.forEach { row -> appendDay(row, events, includePersonalNotes, zone) }
        append("<footer>Generated by Zillit — ${DiaryFormat.fullDate(today)}</footer>")
        append("<script>window.onload = function () { window.print(); };</script></body></html>")
    }

    private fun StringBuilder.appendDay(
        row: ScheduleDayRow,
        events: List<DiaryEvent>,
        includePersonalNotes: Boolean,
        zone: TimeZone,
    ) {
        val onDay = events.filter { it.scheduleDayId == row.block.id && it.filedOn(zone) == row.date }
        val dayEvents = onDay.filter { it.kind == DiaryKind.Event }
        val notes = onDay.filter { it.kind == DiaryKind.Note && (includePersonalNotes || !it.isPersonalNote) }
        val dayOff = row.block.isDayOff
        val typeLabel = if (dayOff) str(S.desktop_bs_day_off_upper) else row.block.typeName.uppercase()
        if (row.isNewBlock) append("<hr class=\"block\">")
        append("<div class=\"day\"><b class=\"num\">${if (dayOff) "—" else row.dayNumber}</b>")
        append("<span class=\"date\">${DiaryFormat.longDate(row.date, zone)}</span>")
        append("<span class=\"type\">${typeLabel.escaped()}</span>")
        append("<span class=\"title\">${row.block.title.escaped()}</span></div>")
        if (dayEvents.isNotEmpty() || notes.isNotEmpty()) appendEntries(dayEvents, notes, zone)
    }

    private fun StringBuilder.appendEntries(dayEvents: List<DiaryEvent>, notes: List<DiaryEvent>, zone: TimeZone) {
        append("<div class=\"entries\">")
        if (dayEvents.isNotEmpty()) {
            append("<div class=\"label\">EVENTS</div>")
            dayEvents.forEach { event ->
                append("<div class=\"event\" style=\"border-color:${event.color.cssColor()}\">")
                append("<b>${DiaryFormat.timeRange(event, zone)}</b> ${event.title.escaped()}")
                if (event.location.isNotBlank()) append("<span class=\"muted\"> — ${event.location.escaped()}</span>")
                append("</div>")
            }
        }
        if (notes.isNotEmpty()) {
            append("<div class=\"label\">NOTES</div><ul>")
            notes.forEach { note ->
                append("<li><b>${note.title.escaped()}</b>")
                if (note.body.isNotBlank()) append(" — ${note.body.escaped()}")
                append("</li>")
            }
            append("</ul>")
        }
        append("</div>")
    }

    private fun String.escaped(): String =
        replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

    /** Only a real `#rrggbb` reaches the stylesheet. */
    private fun String.cssColor(): String = if (Regex("^#[0-9a-fA-F]{6}$").matches(this)) this else "#3498DB"

    private const val NUMBER_WIDTH = 3
    private const val DATE_WIDTH = 16
    private const val TYPE_WIDTH = 11

    private val PRINT_CSS = """
        body{font-family:-apple-system,Helvetica,Arial,sans-serif;color:#222;margin:32px;background:#fff}
        header{text-align:center;padding-bottom:14px;margin-bottom:20px;border-bottom:3px double #000}
        h1{font-size:22px;font-weight:800;letter-spacing:4px;text-transform:uppercase;margin:0 0 4px;
           font-family:Georgia,'Times New Roman',serif}
        header p{font-size:12px;color:#666;margin:0}
        .legend{display:flex;gap:16px;flex-wrap:wrap;font-size:11px;color:#555;margin-bottom:16px}
        .legend span{display:inline-flex;align-items:center;gap:4px}
        .legend i{display:inline-block;width:10px;height:10px;border:1px solid #999}
        hr.block{border:0;border-top:2px solid #000;margin:12px 0 8px}
        .day{display:flex;align-items:baseline;gap:12px;padding:6px 12px;border-bottom:1px solid #ddd}
        .num{font-size:16px;font-family:Georgia,serif;min-width:36px}
        .date{font-size:13px;color:#555;min-width:220px}
        .type{font-size:12px;font-weight:700;letter-spacing:.5px;color:#444}
        .title{font-size:13px;color:#666;flex:1}
        .entries{padding:8px 12px 8px 60px;font-size:12px;border-bottom:1px solid #eee}
        .label{font-size:9px;font-weight:700;letter-spacing:1.5px;color:#888;margin:4px 0 3px}
        .event{margin-bottom:3px;padding-left:8px;border-left:2px solid}
        .muted{color:#888}
        ul{margin:0;padding-left:16px;font-size:11px;color:#444}
        footer{margin-top:24px;padding-top:8px;border-top:1px solid #ccc;font-size:10px;color:#aaa;text-align:center}
        @media print{body{margin:12mm}}
    """.trimIndent()
}
