package com.zillit.desktop.feature.dealmemo.ui.pages.builder

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color
import com.zillit.desktop.core.designsystem.ZillitTheme

/**
 * The one-page builder's tokens (`template-builder.css` and the page's own
 * literals — spec 07 §7.2), light and dark. The wizard steps it hosts are
 * drawn in this skin: flat blocks on one memo card, grey alerts, 39 px
 * controls.
 */
@Immutable
internal data class BuilderPalette(
    val page: Color,
    val card: Color,
    val cardBorder: Color,
    val hairline: Color,
    val divider: Color,
    val band: Color,
    val ink: Color,
    val title: Color,
    val ink2: Color,
    val muted: Color,
    val placeholder: Color,
    val sectionLabel: Color,
    val bandTitle: Color,
    val cta: Color,
    val ctaHover: Color,
    val brand: Color,
    val brandHover: Color,
    val green: Color,
    val greenHover: Color,
    val red: Color,
    val redHover: Color,
    val redInk: Color,
    val redSoft: Color,
    val redBorder: Color,
    val flagWash: Color,
    val flagLabel: Color,
    val noteRed: Color,
    val noteBg: Color,
    val noteBorder: Color,
    val noteInk: Color,
    val pickerBg: Color,
    val pickerBorder: Color,
    val pickerTitle: Color,
    val pickerBody: Color,
    val inputBg: Color,
    val inputBorder: Color,
    val focusBorder: Color,
    val disabledBg: Color,
    val chipBg: Color,
    val chipBorder: Color,
    val chipInk: Color,
    val chipHover: Color,
    val alertBg: Color,
    val alertBorder: Color,
    val alertInk: Color,
    val infoBox: Color,
    val infoBorder: Color,
    val toggleOn: Color,
    val toggleOff: Color,
    val tile: Color,
    val menu: Color,
    val menuBorder: Color,
    val menuDivider: Color,
    val menuHover: Color,
    val menuSelected: Color,
    val dashed: Color,
    val skeleton: Color,
    val header: Color,
    val teal: Color,
    val tealSoft: Color,
    val tealRing: Color,
    val blue: Color,
    val blueSoft: Color,
    val blueRing: Color,
    val purple: Color,
    val purpleSoft: Color,
    val purpleRing: Color,
    val greenInk: Color,
    val greenSoft: Color,
    val greenRing: Color,
    val amberSoft: Color,
    val amberRing: Color,
    val autosaveError: Color,
    /** The rates step's reference tables: header band, row rules, and its figure inks. */
    val tableHead: Color,
    val tableRule: Color,
    val gold: Color,
    val orange: Color,
    val tealInk: Color,
    val purpleInk: Color,
    val scaleBg: Color,
    val scaleBorder: Color,
    val scheduleActive: Color,
    val overrideBg: Color,
    val overrideBorder: Color,
    /** A segmented pill's track and its chosen segment — Holiday Pay's Exclusive / Inclusive. */
    val segmentTrack: Color,
    val segmentActive: Color,
    /** The Setup Hub: its pane, the active tab's wash, idle tab ink, card borders and quiet ink. */
    val hubPane: Color,
    val hubTabActive: Color,
    val hubTabInk: Color,
    val hubBorder: Color,
    val hubMuted: Color,
) {
    companion object {
        val Light = BuilderPalette(
            page = Color(0xFFF8F9FB),
            card = Color.White,
            cardBorder = Color(0xFFE5E7EB),
            hairline = Color(0xFFECECEA),
            divider = Color(0xFFDCDFE5),
            band = Color(0xFFEEF0F4),
            ink = Color(0xFF0F1115),
            title = Color(0xFF1A1E2C),
            ink2 = Color(0xFF4A4D55),
            muted = Color(0xFF8A8D95),
            placeholder = Color(0xFFB8B7B1),
            sectionLabel = Color(0xFFE08600),
            bandTitle = Color(0xFFC26A09),
            cta = Color(0xFFE8861A),
            ctaHover = Color(0xFFD97712),
            brand = Color(0xFFFC9404),
            brandHover = Color(0xFFFDB034),
            green = Color(0xFF1AA463),
            greenHover = Color(0xFF15875A),
            red = Color(0xFFEF4444),
            redHover = Color(0xFFDC2626),
            redInk = Color(0xFFB91C1C),
            redSoft = Color(0xFFFEF2F2),
            redBorder = Color(0xFFFECACA),
            flagWash = Color(0xFFFEF2F2).copy(alpha = 0.6f),
            flagLabel = Color(0xFFDC2626),
            noteRed = Color(0xFFC0392B),
            noteBg = Color(0xFFFDF4E7),
            noteBorder = Color(0xFFF3DDBE),
            noteInk = Color(0xFF8A4D06),
            pickerBg = Color(0xFFFDEEE0),
            pickerBorder = Color(0xFFF6D8B8),
            pickerTitle = Color(0xFF8A3F04),
            pickerBody = Color(0xFF8A4D06),
            inputBg = Color.White,
            inputBorder = Color(0xFFE6E7EA),
            focusBorder = Color(0xFFF6D8A8),
            disabledBg = Color(0xFFF7F7F8),
            chipBg = Color.White,
            chipBorder = Color(0xFFECECEA),
            chipInk = Color(0xFF4A4D55),
            chipHover = Color(0xFFF9FAFB),
            alertBg = Color(0xFFF7F7F8),
            alertBorder = Color(0xFFE6E7EA),
            alertInk = Color(0xFF4A4D55),
            infoBox = Color(0xFFFAFAF6),
            infoBorder = Color(0xFFECECEA),
            toggleOn = Color(0xFFFC9404),
            toggleOff = Color(0xFFD1D5DB),
            tile = Color(0xFFF3F4F6),
            menu = Color.White,
            menuBorder = Color(0xFFE3E2DD),
            menuDivider = Color(0xFFECECEA),
            menuHover = Color(0xFFFAF9F6),
            menuSelected = Color(0xFFFDF2E2),
            dashed = Color(0xFFCFD5DF),
            skeleton = Color(0xFFE5E7EB),
            header = Color(0xFFF8F9FB).copy(alpha = 0.85f),
            teal = Color(0xFF14A394),
            tealSoft = Color(0xFFD9F4F0),
            tealRing = Color(0xFFA8E3D9),
            blue = Color(0xFF2862E0),
            blueSoft = Color(0xFFE9EFFF),
            blueRing = Color(0xFFCBD6F3),
            purple = Color(0xFF7A4CD6),
            purpleSoft = Color(0xFFF1EBFF),
            purpleRing = Color(0xFFDBCDF6),
            greenInk = Color(0xFF0C6A3F),
            greenSoft = Color(0xFFE6F7EE),
            greenRing = Color(0xFFC2E6D3),
            amberSoft = Color(0xFFFDF2E2),
            amberRing = Color(0xFFF6D8A8),
            autosaveError = Color(0xFFC0392B),
            tableHead = Color(0xFFF9FAFB),
            tableRule = Color(0xFFF3F4F6),
            gold = Color(0xFFE8861A),
            orange = Color(0xFFE8861A),
            tealInk = Color(0xFF0D9488),
            purpleInk = Color(0xFF9333EA),
            scaleBg = Color(0xFF1D4186).copy(alpha = 0.05f),
            scaleBorder = Color(0xFF1D4186).copy(alpha = 0.20f),
            scheduleActive = Color(0xFF1D4186),
            overrideBg = Color(0xFFFFFBEB),
            overrideBorder = Color(0xFFFDE68A),
            segmentTrack = Color(0xFFF1EFE9),
            segmentActive = Color.White,
            hubPane = Color(0xFFF8F9FB),
            hubTabActive = Color(0xFFFDF1DF),
            hubTabInk = Color(0xFF6B7280),
            hubBorder = Color(0xFFE2E4E9),
            hubMuted = Color(0xFF9CA3AF),
        )

        val Dark = BuilderPalette(
            page = Color(0xFF14161B),
            card = Color(0xFF141720),
            cardBorder = Color(0xFF1E2535),
            hairline = Color.White.copy(alpha = 0.08f),
            divider = Color(0xFF2A3040),
            band = Color.White.copy(alpha = 0.05f),
            ink = Color(0xFFE8EAF0),
            title = Color.White,
            ink2 = Color(0xFF8B90AA),
            muted = Color(0xFF5A6478),
            placeholder = Color(0xFF5A6478),
            sectionLabel = Color(0xFFE8B84B),
            bandTitle = Color(0xFFE8B84B),
            cta = Color(0xFFE8861A),
            ctaHover = Color(0xFFD97712),
            brand = Color(0xFFFC9404),
            brandHover = Color(0xFFFDB034),
            green = Color(0xFF1AA463),
            greenHover = Color(0xFF15875A),
            red = Color(0xFFEF4444),
            redHover = Color(0xFFDC2626),
            redInk = Color(0xFFFCA5A5),
            redSoft = Color(0xFFEF4444).copy(alpha = 0.08f),
            redBorder = Color(0xFFEF4444).copy(alpha = 0.30f),
            flagWash = Color(0xFFEF4444).copy(alpha = 0.06f),
            flagLabel = Color(0xFFF87171),
            noteRed = Color(0xFFF87171),
            noteBg = Color(0xFFF59E0B).copy(alpha = 0.08f),
            noteBorder = Color(0xFFF59E0B).copy(alpha = 0.25f),
            noteInk = Color(0xFFFBBF24),
            pickerBg = Color(0xFFF59E0B).copy(alpha = 0.08f),
            pickerBorder = Color(0xFFF59E0B).copy(alpha = 0.25f),
            pickerTitle = Color(0xFFFBBF24),
            pickerBody = Color(0xFFFBBF24).copy(alpha = 0.85f),
            inputBg = Color(0xFF1C2030),
            inputBorder = Color.White.copy(alpha = 0.08f),
            focusBorder = Color(0xFFE8B84B).copy(alpha = 0.5f),
            disabledBg = Color.White.copy(alpha = 0.04f),
            chipBg = Color(0xFF1A1D24),
            chipBorder = Color.White.copy(alpha = 0.08f),
            chipInk = Color(0xFF8B95A8),
            chipHover = Color(0xFF1F232C),
            alertBg = Color.White.copy(alpha = 0.04f),
            alertBorder = Color.White.copy(alpha = 0.08f),
            alertInk = Color(0xFF8B90AA),
            infoBox = Color(0xFF0F1115),
            infoBorder = Color.White.copy(alpha = 0.06f),
            toggleOn = Color(0xFFFC9404),
            toggleOff = Color(0xFF3A3F52),
            tile = Color.White.copy(alpha = 0.06f),
            menu = Color(0xFF1A1D23),
            menuBorder = Color.White.copy(alpha = 0.10f),
            menuDivider = Color.White.copy(alpha = 0.06f),
            menuHover = Color(0xFF22262E),
            menuSelected = Color(0xFFE8861A).copy(alpha = 0.12f),
            dashed = Color.White.copy(alpha = 0.14f),
            skeleton = Color.White.copy(alpha = 0.08f),
            header = Color(0xFF14161B).copy(alpha = 0.85f),
            teal = Color(0xFF2DD4BF),
            tealSoft = Color(0xFF14A394).copy(alpha = 0.15f),
            tealRing = Color(0xFF14A394).copy(alpha = 0.30f),
            blue = Color(0xFF60A5FA),
            blueSoft = Color(0xFF3B82F6).copy(alpha = 0.12f),
            blueRing = Color(0xFF3B82F6).copy(alpha = 0.30f),
            purple = Color(0xFFC084FC),
            purpleSoft = Color(0xFFA855F7).copy(alpha = 0.12f),
            purpleRing = Color(0xFFA855F7).copy(alpha = 0.30f),
            greenInk = Color(0xFF4ADE80),
            greenSoft = Color(0xFF1AA463).copy(alpha = 0.10f),
            greenRing = Color(0xFF1AA463).copy(alpha = 0.30f),
            amberSoft = Color(0xFFF59E0B).copy(alpha = 0.12f),
            amberRing = Color(0xFFF59E0B).copy(alpha = 0.30f),
            autosaveError = Color(0xFFE07A6A),
            tableHead = Color(0xFF1C2030),
            tableRule = Color(0xFF1F2436),
            gold = Color(0xFFE8B84B),
            orange = Color(0xFFFB923C),
            tealInk = Color(0xFF2DD4BF),
            purpleInk = Color(0xFFC084FC),
            scaleBg = Color(0xFFFC9404).copy(alpha = 0.05f),
            scaleBorder = Color(0xFFFC9404).copy(alpha = 0.20f),
            scheduleActive = Color(0xFFFC9404),
            overrideBg = Color(0xFFE8B84B).copy(alpha = 0.05f),
            overrideBorder = Color(0xFFE8B84B).copy(alpha = 0.20f),
            segmentTrack = Color(0xFF1C2030),
            segmentActive = Color(0xFF1A1D24),
            hubPane = Color(0xFF0B0D11),
            hubTabActive = Color(0xFFF59E0B).copy(alpha = 0.08f),
            hubTabInk = Color.White.copy(alpha = 0.60f),
            hubBorder = Color.White.copy(alpha = 0.10f),
            hubMuted = Color.White.copy(alpha = 0.45f),
        )
    }
}

internal val bp: BuilderPalette
    @Composable @ReadOnlyComposable get() = if (ZillitTheme.colors.isDark) BuilderPalette.Dark else BuilderPalette.Light
