@file:Suppress("LongMethod") // The dialog's sections read best in source order.

package com.zillit.desktop.feature.sides.ui.pages

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.zillit.desktop.core.designsystem.ZillitTheme
import com.zillit.desktop.core.designsystem.component.ButtonSize
import com.zillit.desktop.core.designsystem.component.ButtonVariant
import com.zillit.desktop.core.designsystem.component.StatusTone
import com.zillit.desktop.core.designsystem.component.ZillitButton
import com.zillit.desktop.core.designsystem.component.ZillitCheckbox
import com.zillit.desktop.core.designsystem.component.ZillitDialogShell
import com.zillit.desktop.core.designsystem.component.ZillitIcon
import com.zillit.desktop.core.designsystem.component.ZillitIconButton
import com.zillit.desktop.core.designsystem.component.ZillitNotice
import com.zillit.desktop.core.designsystem.component.ZillitText
import com.zillit.desktop.core.designsystem.component.ZillitTextField
import com.zillit.desktop.core.designsystem.component.ZillitTooltip
import com.zillit.desktop.core.designsystem.icon.ZillitIcons
import com.zillit.desktop.core.strings.S
import com.zillit.desktop.core.strings.str
import com.zillit.desktop.feature.sides.domain.CallSheetRef
import com.zillit.desktop.feature.sides.domain.ScheduleRef
import com.zillit.desktop.feature.sides.domain.SidesStatus
import com.zillit.desktop.feature.sides.ui.AutoState
import com.zillit.desktop.feature.sides.ui.DocKind
import com.zillit.desktop.feature.sides.ui.SidesEvent
import com.zillit.desktop.feature.sides.ui.components.DraggableSceneOrder
import com.zillit.desktop.feature.sides.ui.components.FieldLabel
import com.zillit.desktop.feature.sides.ui.components.LinkButton
import com.zillit.desktop.feature.sides.ui.components.RadioRow
import com.zillit.desktop.feature.sides.ui.components.SceneChip
import com.zillit.desktop.feature.sides.ui.components.SidesLoader

/**
 * Autogenerate Sides — the web's `AutogenerateSidesModal`: pick or upload
 * a call sheet, see its extracted scenes, optionally rearrange them and
 * attach a schedule, choose how unselected scenes print, then generate
 * and review.
 */
@Composable
internal fun AutogenerateDialog(auto: AutoState, canDownload: Boolean, onEvent: (SidesEvent) -> Unit) {
    val colors = ZillitTheme.colors
    val locked = auto.running || auto.publishing
    ZillitDialogShell(
        title = str(S.sides_autogenerate),
        visible = true,
        onDismiss = { if (!locked) onEvent(SidesEvent.AutoClose) },
        width = 760.dp,
        icon = ZillitIcons.Play,
        actions = if (auto.result != null && auto.result.status.terminal) {
            null
        } else {
            {
                ZillitButton(
                    text = str(S.cancel),
                    onClick = { onEvent(SidesEvent.AutoClose) },
                    variant = ButtonVariant.Tertiary,
                    size = ButtonSize.Small,
                    enabled = !auto.running,
                )
                ZillitTooltip(if (auto.generateDisabled) auto.disabledReason else "") {
                    ZillitButton(
                        text = if (auto.running) str(S.drive_generating) else str(S.sides_generate),
                        onClick = { onEvent(SidesEvent.AutoGenerate) },
                        size = ButtonSize.Small,
                        enabled = !auto.generateDisabled && !auto.running,
                        loading = auto.running,
                        leadingIcon = ZillitIcons.Play,
                    )
                }
            }
        },
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(18.dp)) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(ZillitTheme.shapes.medium)
                    .background(colors.accentSoft)
                    .padding(horizontal = 12.dp, vertical = 8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                ZillitIcon(icon = ZillitIcons.File, tint = colors.accentText, size = 14.dp)
                ZillitText(
                    "${str(S.sides_section_script)}:",
                    style = ZillitTheme.typography.bodySmall,
                    color = colors.accentText,
                )
                ZillitText(
                    text = auto.scriptTitle.ifBlank { "—" },
                    style = ZillitTheme.typography.bodySmall.copy(fontWeight = FontWeight.Bold),
                    color = colors.accentText,
                )
            }
            when {
                auto.result != null || auto.running -> AutoResult(auto, canDownload, onEvent)
                auto.loading -> SidesLoader(str(S.desktop_sides_loading_call_sheets))
                else -> AutoSetup(auto, onEvent)
            }
        }
    }
}

@Composable
private fun AutoSetup(auto: AutoState, onEvent: (SidesEvent) -> Unit) {
    val colors = ZillitTheme.colors

    CallSheetSection(auto, onEvent)

    // The selected sheet's scenes, and the optional rearrange.
    when {
        auto.selectedCallSheetId.isBlank() -> Hint(str(S.desktop_sides_select_call_sheet_continue))
        auto.detailLoading -> ZillitText(
            str(S.desktop_loading_scenes),
            style = ZillitTheme.typography.bodySmall,
            color = colors.textMuted,
        )
        else -> Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
            ScenesBox(auto.scenes)
            ZillitCheckbox(
                checked = auto.rearrange,
                onCheckedChange = { onEvent(SidesEvent.AutoRearrange(it)) },
                label = str(S.desktop_sides_rearrange_order),
            )
            if (auto.rearrange) {
                FieldLabel(str(S.sides_order_hint))
                DraggableSceneOrder(
                    order = auto.order,
                    available = auto.scenes,
                    onChange = { onEvent(SidesEvent.AutoOrder(it)) },
                )
                ZillitTextField(
                    value = auto.orderText,
                    onValueChange = { onEvent(SidesEvent.AutoOrderText(it)) },
                    placeholder = str(S.desktop_sides_scene_order_example),
                )
                ZillitText(
                    text = str(
                        S.desktop_sides_scene_count_list,
                        auto.orderedScenes.size,
                        auto.orderedScenes.joinToString(", "),
                    ),
                    style = ZillitTheme.typography.labelSmall,
                    color = colors.textMuted,
                )
            }
        }
    }

    ScheduleSection(auto, onEvent)

    ModeSection(auto.displayMode) { onEvent(SidesEvent.AutoDisplayMode(it)) }

    // Why Generate is disabled — only once a sheet is picked but has nothing to generate.
    if (auto.selectedCallSheetId.isNotBlank() && !auto.detailLoading && auto.orderedScenes.isEmpty()) {
        ZillitNotice(text = auto.disabledReason, tone = StatusTone.Pending, icon = ZillitIcons.Info)
    }
}

@Composable
private fun CallSheetSection(auto: AutoState, onEvent: (SidesEvent) -> Unit) {
    // Published vs Uploaded; only uploaded rows can be deleted.
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
            FieldLabel(str(S.sides_section_call_sheet))
            Spacer(Modifier.weight(1f))
            ZillitButton(
                text = str(S.desktop_upload_new),
                onClick = { onEvent(SidesEvent.AutoUpload(DocKind.CallSheet)) },
                variant = ButtonVariant.Secondary,
                size = ButtonSize.Small,
                leadingIcon = ZillitIcons.Add,
            )
        }
        if (auto.callSheets.isEmpty()) {
            Hint(str(S.desktop_sides_no_published_call_sheet))
        } else {
            if (auto.publishedSheets.isNotEmpty()) {
                GroupLabel(str(S.cs_published))
                auto.publishedSheets.forEach { CallSheetRow(it, auto, deletable = false, onEvent) }
            }
            if (auto.uploadedSheets.isNotEmpty()) {
                GroupLabel(str(S.sides_uploaded))
                auto.uploadedSheets.forEach { CallSheetRow(it, auto, deletable = true, onEvent) }
            }
        }
    }

}

@Composable
private fun ScheduleSection(auto: AutoState, onEvent: (SidesEvent) -> Unit) {
    val colors = ZillitTheme.colors
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
            FieldLabel(str(S.schedule), optional = true)
            Spacer(Modifier.weight(1f))
            ZillitButton(
                text = str(S.desktop_upload_new),
                onClick = { onEvent(SidesEvent.AutoUpload(DocKind.Schedule)) },
                variant = ButtonVariant.Secondary,
                size = ButtonSize.Small,
                leadingIcon = ZillitIcons.Add,
            )
        }
        RadioRow(
            selected = auto.selectedScheduleId.isBlank(),
            onClick = { onEvent(SidesEvent.AutoSelectSchedule("")) },
        ) {
            ZillitText(
                str(S.desktop_no_schedule),
                style = ZillitTheme.typography.bodySmall,
                color = colors.textSecondary,
            )
        }
        if (auto.publishedSchedules.isNotEmpty()) {
            GroupLabel(str(S.cs_published))
            auto.publishedSchedules.forEach { ScheduleRow(it, auto, onEvent) }
        }
        if (auto.uploadedSchedules.isNotEmpty()) {
            GroupLabel(str(S.sides_uploaded))
            auto.uploadedSchedules.forEach { ScheduleRow(it, auto, onEvent) }
        }
    }

}

@Composable
private fun GroupLabel(text: String) {
    ZillitText(
        text = text.uppercase(),
        style = ZillitTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
        color = ZillitTheme.colors.textMuted,
        modifier = Modifier.padding(top = 4.dp),
    )
}

@Composable
private fun Hint(text: String) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .clip(ZillitTheme.shapes.medium)
            .background(ZillitTheme.colors.surfaceSunken)
            .border(1.dp, ZillitTheme.colors.border, ZillitTheme.shapes.medium)
            .padding(14.dp),
        contentAlignment = Alignment.Center,
    ) {
        ZillitText(text, style = ZillitTheme.typography.bodySmall, color = ZillitTheme.colors.textMuted)
    }
}

@Composable
private fun CallSheetRow(sheet: CallSheetRef, auto: AutoState, deletable: Boolean, onEvent: (SidesEvent) -> Unit) {
    RadioRow(
        selected = auto.selectedCallSheetId == sheet.id,
        onClick = { onEvent(SidesEvent.AutoSelectCallSheet(sheet.id)) },
    ) {
        Column(Modifier.weight(1f)) {
            ZillitText(
                text = sheet.title,
                style = ZillitTheme.typography.bodySmall.copy(fontWeight = FontWeight.Bold),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
            ZillitText(
                "${sheet.scenes.size} scenes",
                style = ZillitTheme.typography.labelSmall,
                color = ZillitTheme.colors.textMuted,
            )
        }
        LinkButton(str(S.view), onClick = { onEvent(SidesEvent.AutoViewCallSheet(sheet)) })
        if (deletable) {
            ZillitIconButton(
                icon = ZillitIcons.Trash,
                contentDescription = str(S.desktop_delete_call_sheet),
                onClick = { onEvent(SidesEvent.AutoAskDeleteCallSheet(sheet)) },
                tint = ZillitTheme.colors.danger,
            )
        }
    }
}

@Composable
private fun ScheduleRow(schedule: ScheduleRef, auto: AutoState, onEvent: (SidesEvent) -> Unit) {
    RadioRow(
        selected = auto.selectedScheduleId == schedule.id,
        onClick = { onEvent(SidesEvent.AutoSelectSchedule(schedule.id)) },
    ) {
        Column(Modifier.weight(1f)) {
            ZillitText(
                text = schedule.title,
                style = ZillitTheme.typography.bodySmall.copy(fontWeight = FontWeight.Bold),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
            ZillitText(
                text = "${schedule.totalDays} days · ${schedule.totalScenes} scenes",
                style = ZillitTheme.typography.labelSmall,
                color = ZillitTheme.colors.textMuted,
            )
        }
        LinkButton(str(S.view), onClick = { onEvent(SidesEvent.AutoViewSchedule(schedule)) })
        ZillitIconButton(
            icon = ZillitIcons.Trash,
            contentDescription = str(S.bs_sched_scope_delete_title),
            onClick = { onEvent(SidesEvent.AutoAskDeleteSchedule(schedule)) },
            tint = ZillitTheme.colors.danger,
        )
    }
}

@OptIn(ExperimentalLayoutApi::class)
@Composable
private fun ScenesBox(scenes: List<String>) {
    val colors = ZillitTheme.colors
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clip(ZillitTheme.shapes.medium)
            .background(colors.surfaceSunken)
            .border(1.dp, colors.border, ZillitTheme.shapes.medium)
            .padding(10.dp),
        verticalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        ZillitText(
            text = "${str(S.sides_extracted_scenes)}:",
            style = ZillitTheme.typography.labelSmall.copy(fontWeight = FontWeight.SemiBold),
            color = colors.textMuted,
        )
        if (scenes.isEmpty()) {
            ZillitText(
                str(S.desktop_sides_no_scenes_in_call_sheet),
                style = ZillitTheme.typography.bodySmall,
                color = colors.textMuted,
            )
        } else {
            FlowRow(
                horizontalArrangement = Arrangement.spacedBy(4.dp),
                verticalArrangement = Arrangement.spacedBy(4.dp),
            ) {
                scenes.forEach { SceneChip(it) }
            }
        }
    }
}

/** The centred review panel — generating, failed, or the View → Publish verbs. */
@Composable
private fun AutoResult(auto: AutoState, canDownload: Boolean, onEvent: (SidesEvent) -> Unit) {
    val colors = ZillitTheme.colors
    val result = auto.result
    Column(
        modifier = Modifier.fillMaxWidth().padding(vertical = 24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        when {
            result == null || !result.status.terminal ->
                SidesLoader(str(S.desktop_sides_generating_under_minute))
            result.status == SidesStatus.Error -> {
                ResultBadge(ZillitIcons.Close, colors.danger)
                ZillitText(str(S.sides_generation_failed), style = ZillitTheme.typography.titleLarge)
                ZillitText(
                    text = result.error.ifBlank { str(S.desktop_sides_generation_error) },
                    style = ZillitTheme.typography.bodySmall,
                    color = colors.textMuted,
                )
                ZillitButton(
                    str(S.close),
                    onClick = { onEvent(SidesEvent.AutoClose) },
                    variant = ButtonVariant.Secondary,
                )
            }
            else -> {
                ResultBadge(ZillitIcons.Check, colors.success)
                ZillitText(str(S.desktop_sides_generated), style = ZillitTheme.typography.titleLarge)
                ZillitText(
                    str(S.desktop_sides_review_draft),
                    style = ZillitTheme.typography.bodySmall,
                    color = colors.textMuted,
                )
                Row(horizontalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.padding(top = 8.dp)) {
                    if (!auto.viewed) {
                        ZillitButton(
                            str(S.desktop_sides_view),
                            onClick = { onEvent(SidesEvent.AutoView) },
                            leadingIcon = ZillitIcons.Eye,
                        )
                    } else {
                        ZillitButton(
                            text = str(S.sides_view_again),
                            onClick = { onEvent(SidesEvent.AutoView) },
                            variant = ButtonVariant.Secondary,
                            leadingIcon = ZillitIcons.Eye,
                        )
                        ZillitButton(
                            text = if (canDownload) str(S.download) else str(S.desktop_download_request_access),
                            onClick = { onEvent(SidesEvent.AutoDownload) },
                            variant = ButtonVariant.Secondary,
                            leadingIcon = ZillitIcons.Download,
                        )
                        ZillitButton(
                            text = if (auto.publishing) str(S.desktop_publishing) else str(S.publish),
                            onClick = { onEvent(SidesEvent.AutoPublish) },
                            loading = auto.publishing,
                            enabled = !auto.publishing,
                            leadingIcon = ZillitIcons.Check,
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun ResultBadge(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    tint: androidx.compose.ui.graphics.Color,
) {
    Box(
        modifier = Modifier.size(64.dp).clip(CircleShape).background(tint.copy(alpha = 0.14f)),
        contentAlignment = Alignment.Center,
    ) {
        ZillitIcon(icon = icon, tint = tint, size = 30.dp)
    }
}
