package com.zillit.desktop.feature.formsignature.domain

import com.zillit.desktop.core.common.ZillitResult

/**
 * The PDF work this tool needs, as interfaces so the implementations (PDFBox,
 * AWT — both JVM-only) stay out of common code and out of the view model's
 * type signatures.
 *
 * ## Coordinate contract
 *
 * Everything here speaks **PDF points, bottom-left origin** — the same space
 * [SignSpot] lives in and the same numbers the backend stores. The renderer
 * reports each page's point size alongside its pixels precisely so callers
 * can convert screen taps into this space and never hold coordinates in two
 * conventions at once.
 */
interface PdfWork {

    /** Renders every page for preview, at [targetWidthPx] wide. */
    fun renderPages(pdf: ByteArray, targetWidthPx: Int): ZillitResult<List<PdfPageImage>>

    /**
     * Flattens [stamps] into the document and returns the new PDF.
     *
     * This is the actual act of signing, done exactly as the web does it:
     * the mark becomes pixels in the document, and only the finished file
     * travels — the server never sees coordinates on this path.
     */
    fun stamp(pdf: ByteArray, stamps: List<PlacedStamp>): ZillitResult<ByteArray>

    /**
     * A drawn signature as a PNG with a transparent background.
     *
     * [strokes] are polylines in a top-left canvas space of
     * [canvasWidth]×[canvasHeight]; the rasteriser flips nothing — the PNG's
     * own orientation is what both the preview and the stamp use.
     */
    fun rasterizeStrokes(
        strokes: List<List<StrokePoint>>,
        canvasWidth: Int,
        canvasHeight: Int,
    ): ZillitResult<ByteArray>
}

/** A page rendered for preview, with the sizes needed to map taps back. */
data class PdfPageImage(
    /** 1-based, matching [SignSpot.page]. */
    val page: Int,
    /** PNG bytes at [widthPx]×[heightPx]. */
    val imageBytes: ByteArray,
    val widthPx: Int,
    val heightPx: Int,
    /** The page's own size in PDF points. */
    val widthPt: Double,
    val heightPt: Double,
) {
    /**
     * A screen position on this page's image, as a [SignSpot] anchor.
     *
     * The vertical flip happens here and only here: pixels count down from
     * the top, points count up from the bottom. [spotHeight] participates
     * because a spot's `y` names its *bottom* edge while a tap names where
     * the *top* of the box should sit.
     */
    fun spotFromTap(
        xPx: Float,
        yPx: Float,
        kind: SignSpotKind,
        spotWidth: Double,
        spotHeight: Double,
    ): SignSpot {
        val scale = widthPt / widthPx
        val xPt = xPx * scale
        val yTopPt = heightPt - (yPx * scale)
        return SignSpot(
            kind = kind,
            page = page,
            x = xPt.coerceIn(0.0, (widthPt - spotWidth).coerceAtLeast(0.0)),
            y = (yTopPt - spotHeight).coerceIn(0.0, (heightPt - spotHeight).coerceAtLeast(0.0)),
            width = spotWidth,
            height = spotHeight,
        )
    }

    /** A spot's rectangle in this image's pixel space: x, y(top), w, h. */
    fun pixelRect(spot: SignSpot): List<Float> {
        val scale = widthPx / widthPt
        val x = (spot.x * scale).toFloat()
        val yTop = ((heightPt - spot.y - spot.height) * scale).toFloat()
        return listOf(x, yTop, (spot.width * scale).toFloat(), (spot.height * scale).toFloat())
    }

    // Regenerated by data-class tooling for the ByteArray field; equality by
    // page and dimensions is what tests and recomposition actually need.
    override fun equals(other: Any?): Boolean = other is PdfPageImage &&
        other.page == page && other.widthPx == widthPx && other.heightPx == heightPx &&
        other.widthPt == widthPt && other.heightPt == heightPt &&
        other.imageBytes.contentEquals(imageBytes)

    override fun hashCode(): Int = page * 31 + imageBytes.size
}

/** A PNG to be flattened into a page at a [SignSpot]-shaped rectangle. */
data class PlacedStamp(
    val pngBytes: ByteArray,
    val spot: SignSpot,
) {
    override fun equals(other: Any?): Boolean = other is PlacedStamp &&
        other.spot == spot && other.pngBytes.contentEquals(pngBytes)

    override fun hashCode(): Int = spot.hashCode() * 31 + pngBytes.size
}

/** One point of a drawn stroke, in canvas pixels, top-left origin. */
data class StrokePoint(val x: Float, val y: Float)
