#!/usr/bin/env python3
"""Generate AhIcons.kt from the web's Account Hub icon bundle.

The web draws the Account Hub with its own 147-glyph stroke set
(`zillit_web/src/accountHub/icons/index.jsx`, itself generated from
`icons/svg/`). This converts that bundle into Compose ImageVectors so the
desktop console shows the same glyph for the same module instead of the
nearest generic icon.

    scripts/gen-ah-icons.py ~/AndroidStudioProjects/zillit_web

Every SVG shape is lowered to path data (line, circle, ellipse, rect,
polyline), because ImageVector only knows paths. A shape with
`fill="currentColor" stroke="none"` becomes a filled path; everything else is
stroked at the bundle's default 1.5 with round caps and joins. The one dashed
arc in the set (`account-hub`) is drawn solid: ImageVector has no dash.
"""
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / (
    "core/designsystem/src/commonMain/kotlin/com/zillit/desktop/core/designsystem/icon/AhIcons.kt"
)


def num(v):
    f = float(v)
    return ("%.3f" % f).rstrip("0").rstrip(".")


def attrs(tag):
    return dict(re.findall(r'([a-z0-9-]+)="([^"]*)"', tag))


def rect(a):
    x, y = float(a.get("x", 0)), float(a.get("y", 0))
    w, h = float(a["width"]), float(a["height"])
    rx = float(a.get("rx", a.get("ry", 0)))
    ry = float(a.get("ry", rx))
    rx, ry = min(rx, w / 2), min(ry, h / 2)
    if rx == 0:
        return f"M{num(x)} {num(y)} H{num(x + w)} V{num(y + h)} H{num(x)} Z"
    return (
        f"M{num(x + rx)} {num(y)} H{num(x + w - rx)} "
        f"A{num(rx)} {num(ry)} 0 0 1 {num(x + w)} {num(y + ry)} V{num(y + h - ry)} "
        f"A{num(rx)} {num(ry)} 0 0 1 {num(x + w - rx)} {num(y + h)} H{num(x + rx)} "
        f"A{num(rx)} {num(ry)} 0 0 1 {num(x)} {num(y + h - ry)} V{num(y + ry)} "
        f"A{num(rx)} {num(ry)} 0 0 1 {num(x + rx)} {num(y)} Z"
    )


def oval(cx, cy, rx, ry):
    return (
        f"M{num(cx - rx)} {num(cy)} A{num(rx)} {num(ry)} 0 1 0 {num(cx + rx)} {num(cy)} "
        f"A{num(rx)} {num(ry)} 0 1 0 {num(cx - rx)} {num(cy)} Z"
    )


def lower(tag, a):
    if tag == "path":
        return " ".join(a["d"].split())
    if tag == "line":
        return f"M{num(a['x1'])} {num(a['y1'])} L{num(a['x2'])} {num(a['y2'])}"
    if tag == "circle":
        r = float(a["r"])
        return oval(float(a["cx"]), float(a["cy"]), r, r)
    if tag == "ellipse":
        return oval(float(a["cx"]), float(a["cy"]), float(a["rx"]), float(a["ry"]))
    if tag == "rect":
        return rect(a)
    if tag == "polyline":
        pts = a["points"].replace(",", " ").split()
        pairs = [f"{num(pts[i])} {num(pts[i + 1])}" for i in range(0, len(pts), 2)]
        return "M" + " L".join(pairs)
    raise ValueError(f"unhandled <{tag}>")


def pascal(name):
    return "".join(p[:1].upper() + p[1:] for p in name.split("-"))


def kotlin_string(s):
    # Keep every generated line inside detekt's 120 columns.
    parts, line = [], ""
    for token in s.split(" "):
        candidate = f"{line} {token}" if line else token
        if len(candidate) > 80 and line:
            parts.append(line + " ")
            line = token
        else:
            line = candidate
    parts.append(line)
    return " +\n                ".join(f'"{p}"' for p in parts)


TEMPLATE = '''package com.zillit.desktop.core.designsystem.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

// GENERATED by scripts/gen-ah-icons.py from zillit_web/src/accountHub/icons/index.jsx.
// Do not hand-edit: re-run the script when the web's bundle changes.

/**
 * The Account Hub's own glyph set — @COUNT@ 24×24 stroke icons the web
 * drew for exactly these modules (purchase order, invoice, card and cash
 * expense, payroll, cost report, ledger, vendor, approver, …).
 *
 * The console used [ZillitIcons]' nearest generic shape for each row, so
 * Invoices and Bible Report were the same page glyph and Payroll and Bank
 * Reconciliation the same bank; the web gives each module its own. Tint these
 * like any other icon — every path is drawn in black and [ZillitIcon] recolours
 * it. Built lazily: the console uses a handful of the set.
 */
@Suppress("LargeClass") // A generated glyph table; one property per icon is the API.
object AhIcons {

@BODY@
    private val byName: Map<String, () -> ImageVector> = mapOf(
@NAMES@,
    )

    /** A glyph by its web name (`"purchase-order"`), for callers that hold the name as data. */
    fun named(name: String): ImageVector? = byName[name]?.invoke()
}

private class GlyphPart(val pathData: String, val filled: Boolean)

private fun s(pathData: String) = GlyphPart(pathData, filled = false)

private fun f(pathData: String) = GlyphPart(pathData, filled = true)

private const val VIEWPORT = 24f

/** The bundle's default stroke (`ahIcon`'s `w`), not the 1.25 the source SVGs carry. */
private const val STROKE = 1.5f

private fun glyph(name: String, vararg parts: GlyphPart): ImageVector =
    ImageVector.Builder(
        name = "Ah.$name",
        defaultWidth = VIEWPORT.dp,
        defaultHeight = VIEWPORT.dp,
        viewportWidth = VIEWPORT,
        viewportHeight = VIEWPORT,
    ).apply {
        parts.forEach { part ->
            addPath(
                pathData = addPathNodes(part.pathData),
                fill = if (part.filled) SolidColor(Color.Black) else null,
                stroke = if (part.filled) null else SolidColor(Color.Black),
                strokeLineWidth = if (part.filled) 0f else STROKE,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }.build()
'''


def main():
    web = Path(sys.argv[1] if len(sys.argv) > 1 else "~/AndroidStudioProjects/zillit_web").expanduser()
    src = (web / "src/accountHub/icons/index.jsx").read_text()
    body = src[src.index("const PATHS = {"): src.index("\n};", src.index("const PATHS = {"))]
    entries = re.findall(r"^  '([a-z0-9-]+)': `(.*)`,$", body, re.M)
    if len(entries) < 100:
        sys.exit(f"parsed only {len(entries)} icons — has the bundle's shape changed?")

    out = []
    for name, svg in entries:
        parts = []
        for tag, rest in re.findall(r"<([a-z]+)([^>]*)>", svg):
            a = attrs(rest)
            filled = a.get("fill") == "currentColor" and a.get("stroke") == "none"
            fn = "f" if filled else "s"
            parts.append(f"{fn}({kotlin_string(lower(tag, a))})")
        joined = ",\n            ".join(parts)
        out.append(
            f"    /** Web `{name}`. */\n"
            f"    val {pascal(name)}: ImageVector by lazy {{\n"
            f"        glyph(\n"
            f"            \"{name}\",\n"
            f"            {joined},\n"
            f"        )\n"
            f"    }}\n"
        )

    body_kt = "\n".join(out)
    names = ",\n".join(f'        "{n}" to {{ {pascal(n)} }}' for n, _ in entries)
    OUT.write_text(
        TEMPLATE.replace("@COUNT@", str(len(entries)))
        .replace("@BODY@", body_kt)
        .replace("@NAMES@", names)
    )
    print(f"wrote {len(entries)} icons to {OUT}")


if __name__ == "__main__":
    main()
