#!/usr/bin/env python3
"""
Copies the Android client's string resources into the desktop app and
regenerates the key catalogue.

    scripts/sync-android-strings.py [path/to/ZillitAndroidV20]

What it does:

  1. Reads `app/src/main/res/values/strings*.xml` (English, several files)
     and every `values-<lang>/strings.xml` from the Android project.
  2. Drops anything that is not user-facing text: `translatable="false"`
     entries and anything that looks like a credential (`*api_key*`). The
     Android file carries a Maps key in a <string>; it must never reach a
     desktop jar.
  3. Writes one clean XML per language to
     `core/strings/src/jvmMain/resources/i18n/strings-<lang>.xml`, keeping
     Android's element shapes (<string>, <plurals>, <string-array>) so the
     desktop parser and the Android resource compiler read the same text.
  4. Regenerates `core/strings/.../S.kt`: one constant per key, so a typo in
     a key is a compile error rather than an English fallback nobody notices.
     Keys from `i18n/desktop-en.xml` (desktop-only text, hand-maintained) are
     included; that file is never overwritten.

Re-run whenever the Android strings change. The output is deterministic, so
a re-run with no upstream change produces no diff.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ANDROID = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / "ZillitAndroidV20"
RES = ANDROID / "app" / "src" / "main" / "res"
OUT = ROOT / "core" / "strings" / "src" / "jvmMain" / "resources" / "i18n"
S_KT = ROOT / "core" / "strings" / "src" / "commonMain" / "kotlin" / "com" / "zillit" / "desktop" / "core" / "strings" / "S.kt"

SECRET = re.compile(r"api_key", re.IGNORECASE)
KOTLIN_HARD_KEYWORDS = {
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
    "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
    "true", "try", "typealias", "typeof", "val", "var", "when", "while",
}


def wanted(elem) -> bool:
    name = elem.get("name")
    if not name:
        return False
    if elem.get("translatable") == "false":
        return False
    if SECRET.search(name):
        return False
    if elem.tag == "string":
        # A blank string is a key with nothing to show; the reader treats it
        # as missing, so shipping it only makes the miss harder to see.
        return bool((elem.text or "").strip()) or len(elem)
    return elem.tag in ("plurals", "string-array")


def load(paths):
    """name -> element, later files winning on a duplicate name."""
    entries = {}
    for path in paths:
        root = ET.parse(path).getroot()
        for elem in root:
            if wanted(elem):
                entries[elem.get("name")] = elem
    return entries


def write(lang: str, entries: dict) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by scripts/sync-android-strings.py from the Android client. Do not edit. -->", "<resources>"]
    for name in sorted(entries):
        elem = entries[name]
        elem.attrib.pop("translatable", None)
        elem.attrib.pop("formatted", None)
        elem.tail = None
        text = ET.tostring(elem, encoding="unicode")
        lines.append("    " + text.strip())
    lines.append("</resources>")
    (OUT / f"strings-{lang}.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def kotlin_name(key: str) -> str:
    return f"`{key}`" if key in KOTLIN_HARD_KEYWORDS else key


def write_keys(keys: set) -> None:
    S_KT.parent.mkdir(parents=True, exist_ok=True)
    header = '''@file:Suppress(
    // Generated: one constant per Android string key. Nothing here is logic.
    "LargeClass",
    "MaxLineLength",
    "ObjectPropertyNaming",
    "ConstPropertyName",
    "UndocumentedPublicProperty",
    "ktlint",
)

package com.zillit.desktop.core.strings

/**
 * Every key the bundled string catalogue knows — GENERATED by
 * `scripts/sync-android-strings.py`, never edited by hand.
 *
 * The constant's value is the key itself, so `str(S.start_project)` reads the
 * same text Android shows for `R.string.start_project`. A key that is not here
 * is a key that no language has; a typo at a call site is a compile error
 * rather than an English fallback nobody notices.
 */
object S {
'''
    body = "".join(f'    const val {kotlin_name(k)}: String = "{k}"\n' for k in sorted(keys))
    S_KT.write_text(header + body + "}\n", encoding="utf-8")


def regenerate_keys_only() -> None:
    """Rebuilds S.kt from the already-synced English files — no Android read.

    What `add-desktop-string.py` calls: parsing two files takes a tenth of a
    second, parsing 22 Android languages takes seconds, and the desktop key
    set is the only thing an add changes.
    """
    keys = set(load([OUT / "strings-en.xml"]))
    desktop = OUT / "desktop-en.xml"
    if desktop.is_file():
        keys |= set(load([desktop]))
    write_keys(keys)


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] == "--keys-only":
        regenerate_keys_only()
        return
    if not RES.is_dir():
        sys.exit(f"Android resources not found at {RES}")
    english = load(sorted((RES / "values").glob("strings*.xml")))
    write("en", english)
    keys = set(english)
    languages = ["en"]
    for folder in sorted(RES.glob("values-*")):
        code = folder.name[len("values-"):]
        # Only language qualifiers: skip values-night, values-w600dp, values-v23…
        if not re.fullmatch(r"[a-z]{2,3}(-r[A-Z]{2})?", code):
            continue
        source = folder / "strings.xml"
        if not source.is_file():
            continue
        entries = load([source])
        # Nothing a language file adds that English lacks is reachable from a
        # key constant, and nothing it lacks is a problem — the reader falls
        # back to English per key.
        write(code, {k: v for k, v in entries.items() if k in english})
        languages.append(code)
    desktop = OUT / "desktop-en.xml"
    if desktop.is_file():
        keys |= set(load([desktop]))
    write_keys(keys)
    print(f"{len(english)} keys, languages: {' '.join(languages)}")


if __name__ == "__main__":
    main()
