package com.zillit.desktop.feature.sides.ui

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInHorizontally
import androidx.compose.animation.slideOutHorizontally
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import com.zillit.desktop.core.designsystem.ZillitTheme
import com.zillit.desktop.core.designsystem.component.ButtonSize
import com.zillit.desktop.core.designsystem.component.ButtonVariant
import com.zillit.desktop.core.designsystem.component.StatusTone
import com.zillit.desktop.core.designsystem.component.ZillitButton
import com.zillit.desktop.core.designsystem.component.ZillitNotice
import com.zillit.desktop.core.designsystem.component.ZillitPageHeader
import com.zillit.desktop.core.designsystem.icon.ZillitIcons
import com.zillit.desktop.core.strings.S
import com.zillit.desktop.core.strings.str
import com.zillit.desktop.feature.sides.ui.components.SidesSegmented
import com.zillit.desktop.feature.sides.ui.pages.AutogenerateDialog
import com.zillit.desktop.feature.sides.ui.pages.GeneratePage
import com.zillit.desktop.feature.sides.ui.pages.ScriptsPage
import com.zillit.desktop.feature.sides.ui.pages.SidesDialogs
import com.zillit.desktop.feature.sides.ui.pages.SidesListPage
import com.zillit.desktop.feature.sides.ui.pages.SidesPdfOverlay

/**
 * The Sides tool — the web's `SidesApp` shell over its three screens.
 *
 * Header, then the `Sides | Script` switch with the page's actions on the
 * right; the generate form stacks over the list as a full page. Every
 * posting and download control is on screen for every viewer — the
 * handler asks an admin when the right is missing (ZL-19714).
 */
@Composable
fun SidesScreen(state: SidesUiState, onEvent: (SidesEvent) -> Unit) {
    val colors = ZillitTheme.colors
    Box(Modifier.fillMaxSize().background(colors.canvas)) {
        AnimatedContent(
            targetState = state.generate != null,
            transitionSpec = {
                if (targetState) {
                    (fadeIn() + slideInHorizontally { it / SLIDE_FRACTION }) togetherWith
                        (fadeOut() + slideOutHorizontally { -it / SLIDE_FRACTION })
                } else {
                    (fadeIn() + slideInHorizontally { -it / SLIDE_FRACTION }) togetherWith
                        (fadeOut() + slideOutHorizontally { it / SLIDE_FRACTION })
                }
            },
            label = "sidesPage",
        ) { generating ->
            val form = state.generate
            if (generating && form != null) {
                GeneratePage(form = form, canDownload = state.viewer.mayDownload, onEvent = onEvent)
            } else {
                ListShell(state, onEvent)
            }
        }
        state.auto?.let { AutogenerateDialog(it, canDownload = state.viewer.mayDownload, onEvent = onEvent) }
        SidesDialogs(state.dialog, onEvent)
        state.pdf?.let { SidesPdfOverlay(it, canDownload = state.viewer.mayDownload, onEvent = onEvent) }
    }
}

@Composable
private fun ListShell(state: SidesUiState, onEvent: (SidesEvent) -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize().padding(
            horizontal = ZillitTheme.spacing.xl,
            vertical = ZillitTheme.spacing.lg,
        ),
        verticalArrangement = Arrangement.spacedBy(ZillitTheme.spacing.lg),
    ) {
        ZillitPageHeader(
            eyebrow = str(S.recce_breadcrumb),
            title = str(S.txt_sides),
            description = str(S.desktop_sides_module_description),
            actions = {
                ZillitButton(
                    text = str(S.refresh_text),
                    onClick = { onEvent(SidesEvent.Refresh) },
                    variant = ButtonVariant.Tertiary,
                    size = ButtonSize.Small,
                    leadingIcon = ZillitIcons.Reload,
                    loading = state.loading,
                )
            },
        )
        if (state.viewer.isBlocked) {
            ZillitNotice(
                text = str(S.desktop_sides_no_access),
                tone = StatusTone.Pending,
                icon = ZillitIcons.Info,
            )
            return@Column
        }
        Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
            SidesSegmented(active = state.destination, onSelect = { onEvent(SidesEvent.Open(it)) })
            Spacer(Modifier.weight(1f))
            PageActions(state.destination, onEvent)
        }
        AnimatedContent(
            targetState = state.destination,
            transitionSpec = {
                (fadeIn() + slideInHorizontally { SLIDE_PX }) togetherWith
                    (fadeOut() + slideOutHorizontally { -SLIDE_PX })
            },
            label = "sidesSurface",
        ) { destination ->
            Box(Modifier.fillMaxSize()) {
                when (destination) {
                    SidesDestination.Sides -> SidesListPage(state.list, onEvent)
                    SidesDestination.Scripts -> ScriptsPage(state.scripts, onEvent)
                }
            }
        }
    }
}

/** The segment's own verbs, on the right of the switch — the web's `actions` slot. */
@Composable
private fun PageActions(destination: SidesDestination, onEvent: (SidesEvent) -> Unit) {
    Row(horizontalArrangement = Arrangement.spacedBy(ZillitTheme.spacing.sm)) {
        when (destination) {
            SidesDestination.Sides -> {
                ZillitButton(
                    text = str(S.sides_autogenerate),
                    onClick = { onEvent(SidesEvent.OpenAutogenerate) },
                    leadingIcon = ZillitIcons.Play,
                )
                ZillitButton(
                    text = str(S.sides_generate),
                    onClick = { onEvent(SidesEvent.OpenGenerate) },
                    variant = ButtonVariant.Secondary,
                    leadingIcon = ZillitIcons.Add,
                )
            }
            SidesDestination.Scripts -> ZillitButton(
                text = str(S.sides_add_script),
                onClick = { onEvent(SidesEvent.AskAddScript) },
                leadingIcon = ZillitIcons.Add,
            )
        }
    }
}

private const val SLIDE_FRACTION = 20
private const val SLIDE_PX = 24
